package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:13:34 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllCpeCejpjD generated by hbm2java
 */
@Entity
@Table(name="m4sll_cpe_cejpj_d"
            ,schema="sll"
      )
public class M4sllCpeCejpjD  implements java.io.Serializable {


    private M4sllCpeCejpjDId id;
    private String ccdSumillaSeguimiento;
    private Date ccdFechaSeguimiento;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;

    public M4sllCpeCejpjD() {
    }


    public M4sllCpeCejpjD(M4sllCpeCejpjDId id) {
        this.id = id;
    }
    public M4sllCpeCejpjD(M4sllCpeCejpjDId id, String ccdSumillaSeguimiento, Date ccdFechaSeguimiento, String idApprole, String idSecuser, Date dtLastUpdate) {
        this.id = id;
        this.ccdSumillaSeguimiento = ccdSumillaSeguimiento;
        this.ccdFechaSeguimiento = ccdFechaSeguimiento;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="litIdLitigio", column=@Column(name="lit_id_litigio", nullable=false, length=10) ),
        @AttributeOverride(name="ccdIdSecuencia", column=@Column(name="ccd_id_secuencia", nullable=false) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllCpeCejpjDId getId() {
        return this.id;
    }

    public void setId(M4sllCpeCejpjDId id) {
        this.id = id;
    }


    @Column(name="ccd_sumilla_seguimiento", length=4000)
    public String getCcdSumillaSeguimiento() {
        return this.ccdSumillaSeguimiento;
    }

    public void setCcdSumillaSeguimiento(String ccdSumillaSeguimiento) {
        this.ccdSumillaSeguimiento = ccdSumillaSeguimiento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ccd_fecha_seguimiento", length=22)
    public Date getCcdFechaSeguimiento() {
        return this.ccdFechaSeguimiento;
    }

    public void setCcdFechaSeguimiento(Date ccdFechaSeguimiento) {
        this.ccdFechaSeguimiento = ccdFechaSeguimiento;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }




}


