package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:10:33 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpRoles generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_roles"
            ,schema="sll"
      )
public class M4sllTpRoles  implements java.io.Serializable {


    private M4sllTpRolesId id;
    private String tprNmTpRol;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tprDtStart;
    private Date tprDtEnd;

    public M4sllTpRoles() {
    }


    public M4sllTpRoles(M4sllTpRolesId id) {
        this.id = id;
    }
    public M4sllTpRoles(M4sllTpRolesId id, String tprNmTpRol, String idApprole, String idSecuser, Date dtLastUpdate, Date tprDtStart, Date tprDtEnd) {
        this.id = id;
        this.tprNmTpRol = tprNmTpRol;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tprDtStart = tprDtStart;
        this.tprDtEnd = tprDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tprIdTpRol", column=@Column(name="tpr_id_tp_rol", nullable=false) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpRolesId getId() {
        return this.id;
    }

    public void setId(M4sllTpRolesId id) {
        this.id = id;
    }


    @Column(name="tpr_nm_tp_rol", length=254)
    public String getTprNmTpRol() {
        return this.tprNmTpRol;
    }

    public void setTprNmTpRol(String tprNmTpRol) {
        this.tprNmTpRol = tprNmTpRol;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpr_dt_start", length=22)
    public Date getTprDtStart() {
        return this.tprDtStart;
    }

    public void setTprDtStart(Date tprDtStart) {
        this.tprDtStart = tprDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpr_dt_end", length=22)
    public Date getTprDtEnd() {
        return this.tprDtEnd;
    }

    public void setTprDtEnd(Date tprDtEnd) {
        this.tprDtEnd = tprDtEnd;
    }




}


