package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:07:47 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpStatus generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_status"
            ,schema="sll"
      )
public class M4sllTpStatus  implements java.io.Serializable {


    private M4sllTpStatusId id;
    private String tplIdTpLitigio;
    private String tstNmTpStatus;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tstDtStart;
    private Date tstDtEnd;

    public M4sllTpStatus() {
    }


    public M4sllTpStatus(M4sllTpStatusId id) {
        this.id = id;
    }
    public M4sllTpStatus(M4sllTpStatusId id, String tplIdTpLitigio, String tstNmTpStatus, String idApprole, String idSecuser, Date dtLastUpdate, Date tstDtStart, Date tstDtEnd) {
        this.id = id;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.tstNmTpStatus = tstNmTpStatus;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tstDtStart = tstDtStart;
        this.tstDtEnd = tstDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tstIdTpStatus", column=@Column(name="tst_id_tp_status", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpStatusId getId() {
        return this.id;
    }

    public void setId(M4sllTpStatusId id) {
        this.id = id;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="tst_nm_tp_status", length=254)
    public String getTstNmTpStatus() {
        return this.tstNmTpStatus;
    }

    public void setTstNmTpStatus(String tstNmTpStatus) {
        this.tstNmTpStatus = tstNmTpStatus;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tst_dt_start", length=22)
    public Date getTstDtStart() {
        return this.tstDtStart;
    }

    public void setTstDtStart(Date tstDtStart) {
        this.tstDtStart = tstDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tst_dt_end", length=22)
    public Date getTstDtEnd() {
        return this.tstDtEnd;
    }

    public void setTstDtEnd(Date tstDtEnd) {
        this.tstDtEnd = tstDtEnd;
    }




}


