package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTribunales generated by hbm2java
 */
@Entity
@Table(name="m4sll_tribunales"
            ,schema="sll"
      )
public class M4sllTribunales  implements java.io.Serializable {


    private M4sllTribunalesId id;
    private String triNmTribunal;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String tplIdTpLitigio;
    private String stdIdSubGeoDiv;
    private String stdIdGeoPlace;
    private Date triDtStart;
    private Date triDtEnd;

    public M4sllTribunales() {
    }


    public M4sllTribunales(M4sllTribunalesId id) {
        this.id = id;
    }
    public M4sllTribunales(M4sllTribunalesId id, String triNmTribunal, String idApprole, String idSecuser, Date dtLastUpdate, String tplIdTpLitigio, String stdIdSubGeoDiv, String stdIdGeoPlace, Date triDtStart, Date triDtEnd) {
        this.id = id;
        this.triNmTribunal = triNmTribunal;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.stdIdSubGeoDiv = stdIdSubGeoDiv;
        this.stdIdGeoPlace = stdIdGeoPlace;
        this.triDtStart = triDtStart;
        this.triDtEnd = triDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="triIdTribunal", column=@Column(name="tri_id_tribunal", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTribunalesId getId() {
        return this.id;
    }

    public void setId(M4sllTribunalesId id) {
        this.id = id;
    }


    @Column(name="tri_nm_tribunal", length=254)
    public String getTriNmTribunal() {
        return this.triNmTribunal;
    }

    public void setTriNmTribunal(String triNmTribunal) {
        this.triNmTribunal = triNmTribunal;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="std_id_sub_geo_div", length=8)
    public String getStdIdSubGeoDiv() {
        return this.stdIdSubGeoDiv;
    }

    public void setStdIdSubGeoDiv(String stdIdSubGeoDiv) {
        this.stdIdSubGeoDiv = stdIdSubGeoDiv;
    }


    @Column(name="std_id_geo_place", length=9)
    public String getStdIdGeoPlace() {
        return this.stdIdGeoPlace;
    }

    public void setStdIdGeoPlace(String stdIdGeoPlace) {
        this.stdIdGeoPlace = stdIdGeoPlace;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tri_dt_start", length=22)
    public Date getTriDtStart() {
        return this.triDtStart;
    }

    public void setTriDtStart(Date triDtStart) {
        this.triDtStart = triDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tri_dt_end", length=22)
    public Date getTriDtEnd() {
        return this.triDtEnd;
    }

    public void setTriDtEnd(Date triDtEnd) {
        this.triDtEnd = triDtEnd;
    }




}


