package com.prosegur.sllpe.domain;
// Generated 26 mar. 2021 15:31:49 by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpDocLitig generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_doc_litig"
            ,schema="sll"
      )
public class M4sllTpDocLitig  implements java.io.Serializable {


    private M4sllTpDocLitigId id;
    private String tdlNmTpDocLitigio;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String tplIdTpLitigio;
    private Date tdlDtEnd;
    private Date tdlDtStart;

    public M4sllTpDocLitig() {
    }


    public M4sllTpDocLitig(M4sllTpDocLitigId id) {
        this.id = id;
    }
    public M4sllTpDocLitig(M4sllTpDocLitigId id, String tdlNmTpDocLitigio, String idApprole, String idSecuser, Date dtLastUpdate, String tplIdTpLitigio, Date tdlDtEnd, Date tdlDtStart) {
        this.id = id;
        this.tdlNmTpDocLitigio = tdlNmTpDocLitigio;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.tdlDtEnd = tdlDtEnd;
        this.tdlDtStart = tdlDtStart;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tdlIdTpDocLitigio", column=@Column(name="tdl_id_tp_doc_litigio", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpDocLitigId getId() {
        return this.id;
    }

    public void setId(M4sllTpDocLitigId id) {
        this.id = id;
    }


    @Column(name="tdl_nm_tp_doc_litigio", length=254)
    public String getTdlNmTpDocLitigio() {
        return this.tdlNmTpDocLitigio;
    }

    public void setTdlNmTpDocLitigio(String tdlNmTpDocLitigio) {
        this.tdlNmTpDocLitigio = tdlNmTpDocLitigio;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tdl_dt_end", length=22)
    public Date getTdlDtEnd() {
        return this.tdlDtEnd;
    }

    public void setTdlDtEnd(Date tdlDtEnd) {
        this.tdlDtEnd = tdlDtEnd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tdl_dt_start", length=22)
    public Date getTdlDtStart() {
        return this.tdlDtStart;
    }

    public void setTdlDtStart(Date tdlDtStart) {
        this.tdlDtStart = tdlDtStart;
    }




}


