package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpValEcoId generated by hbm2java
 */
@Embeddable
public class M4sllTpValEcoId  implements java.io.Serializable {


    private String tveIdValEco;
    private String idOrganization;

    public M4sllTpValEcoId() {
    }

    public M4sllTpValEcoId(String tveIdValEco, String idOrganization) {
        this.tveIdValEco = tveIdValEco;
        this.idOrganization = idOrganization;
    }



    @Column(name="tve_id_val_eco", nullable=false, length=3)
    public String getTveIdValEco() {
        return this.tveIdValEco;
    }

    public void setTveIdValEco(String tveIdValEco) {
        this.tveIdValEco = tveIdValEco;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpValEcoId) ) return false;
        M4sllTpValEcoId castOther = ( M4sllTpValEcoId ) other;

        return ( (this.getTveIdValEco()==castOther.getTveIdValEco()) || ( this.getTveIdValEco()!=null && castOther.getTveIdValEco()!=null && this.getTveIdValEco().equals(castOther.getTveIdValEco()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTveIdValEco() == null ? 0 : this.getTveIdValEco().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


