package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:09:46 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpMotivo generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_motivo"
            ,schema="sll"
      )
public class M4sllTpMotivo  implements java.io.Serializable {


    private M4sllTpMotivoId id;
    private String tmoNmTpMotivo;
    private String tplIdTpLitigio;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tmoDtStart;
    private Date tmoDtEnd;

    public M4sllTpMotivo() {
    }


    public M4sllTpMotivo(M4sllTpMotivoId id) {
        this.id = id;
    }
    public M4sllTpMotivo(M4sllTpMotivoId id, String tmoNmTpMotivo, String tplIdTpLitigio, String idApprole, String idSecuser, Date dtLastUpdate, Date tmoDtStart, Date tmoDtEnd) {
        this.id = id;
        this.tmoNmTpMotivo = tmoNmTpMotivo;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tmoDtStart = tmoDtStart;
        this.tmoDtEnd = tmoDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tmoIdTpMotivo", column=@Column(name="tmo_id_tp_motivo", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpMotivoId getId() {
        return this.id;
    }

    public void setId(M4sllTpMotivoId id) {
        this.id = id;
    }


    @Column(name="tmo_nm_tp_motivo", length=254)
    public String getTmoNmTpMotivo() {
        return this.tmoNmTpMotivo;
    }

    public void setTmoNmTpMotivo(String tmoNmTpMotivo) {
        this.tmoNmTpMotivo = tmoNmTpMotivo;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tmo_dt_start", length=22)
    public Date getTmoDtStart() {
        return this.tmoDtStart;
    }

    public void setTmoDtStart(Date tmoDtStart) {
        this.tmoDtStart = tmoDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tmo_dt_end", length=22)
    public Date getTmoDtEnd() {
        return this.tmoDtEnd;
    }

    public void setTmoDtEnd(Date tmoDtEnd) {
        this.tmoDtEnd = tmoDtEnd;
    }




}


