package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpCompromisId generated by hbm2java
 */
@Embeddable
public class M4sllTpCompromisId  implements java.io.Serializable {


    private String tcoIdTpCompromiso;
    private String idOrganization;

    public M4sllTpCompromisId() {
    }

    public M4sllTpCompromisId(String tcoIdTpCompromiso, String idOrganization) {
        this.tcoIdTpCompromiso = tcoIdTpCompromiso;
        this.idOrganization = idOrganization;
    }



    @Column(name="tco_id_tp_compromiso", nullable=false, length=3)
    public String getTcoIdTpCompromiso() {
        return this.tcoIdTpCompromiso;
    }

    public void setTcoIdTpCompromiso(String tcoIdTpCompromiso) {
        this.tcoIdTpCompromiso = tcoIdTpCompromiso;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpCompromisId) ) return false;
        M4sllTpCompromisId castOther = ( M4sllTpCompromisId ) other;

        return ( (this.getTcoIdTpCompromiso()==castOther.getTcoIdTpCompromiso()) || ( this.getTcoIdTpCompromiso()!=null && castOther.getTcoIdTpCompromiso()!=null && this.getTcoIdTpCompromiso().equals(castOther.getTcoIdTpCompromiso()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTcoIdTpCompromiso() == null ? 0 : this.getTcoIdTpCompromiso().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


