package com.prosegur.sllpe.domain;
// Generated 23 mar. 2021 16:38:46 by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllCompromisos generated by hbm2java
 */
@Entity
@Table(name="m4sll_compromisos"
            ,schema="sll"
      )
public class M4sllCompromisos  implements java.io.Serializable {


    private M4sllCompromisosId id;
    private Long mabSecuencia;
    private String tfaIdTpFase;
    private String corIdCompResultado;
    private Date comFecha;
    private String comObservacion;
    private String coeIdCompEstado;
    private Date comDtEnd;
    private String comResponsable;
    private Date comDtInicio;
    private String comActuacion;
    private String comNotas;
    private Date comDtInicioTermino;
    private Date comDtFinTermino;
    private Date comDtRegistro;
    private String comUrlDocumento;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String comNmDocumento;
    private Long comSecuencial;

    public M4sllCompromisos() {
    }


    public M4sllCompromisos(M4sllCompromisosId id) {
        this.id = id;
    }
    public M4sllCompromisos(M4sllCompromisosId id, Long mabSecuencia, String tfaIdTpFase, String corIdCompResultado, Date comFecha, String comObservacion, String coeIdCompEstado, Date comDtEnd, String comResponsable, Date comDtInicio, String comActuacion, String comNotas, Date comDtInicioTermino, Date comDtFinTermino, Date comDtRegistro, String comUrlDocumento, String idApprole, String idSecuser, Date dtLastUpdate, String comNmDocumento, Long comSecuencial) {
        this.id = id;
        this.mabSecuencia = mabSecuencia;
        this.tfaIdTpFase = tfaIdTpFase;
        this.corIdCompResultado = corIdCompResultado;
        this.comFecha = comFecha;
        this.comObservacion = comObservacion;
        this.coeIdCompEstado = coeIdCompEstado;
        this.comDtEnd = comDtEnd;
        this.comResponsable = comResponsable;
        this.comDtInicio = comDtInicio;
        this.comActuacion = comActuacion;
        this.comNotas = comNotas;
        this.comDtInicioTermino = comDtInicioTermino;
        this.comDtFinTermino = comDtFinTermino;
        this.comDtRegistro = comDtRegistro;
        this.comUrlDocumento = comUrlDocumento;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.comNmDocumento = comNmDocumento;
        this.comSecuencial = comSecuencial;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tcoIdTpCompromiso", column=@Column(name="tco_id_tp_compromiso", nullable=false, length=3) ),
        @AttributeOverride(name="litIdLitigio", column=@Column(name="lit_id_litigio", nullable=false, length=10) ),
        @AttributeOverride(name="comSecuencia", column=@Column(name="com_secuencia", nullable=false) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllCompromisosId getId() {
        return this.id;
    }

    public void setId(M4sllCompromisosId id) {
        this.id = id;
    }


    @Column(name="mab_secuencia")
    public Long getMabSecuencia() {
        return this.mabSecuencia;
    }

    public void setMabSecuencia(Long mabSecuencia) {
        this.mabSecuencia = mabSecuencia;
    }


    @Column(name="tfa_id_tp_fase", length=3)
    public String getTfaIdTpFase() {
        return this.tfaIdTpFase;
    }

    public void setTfaIdTpFase(String tfaIdTpFase) {
        this.tfaIdTpFase = tfaIdTpFase;
    }


    @Column(name="cor_id_comp_resultado", length=3)
    public String getCorIdCompResultado() {
        return this.corIdCompResultado;
    }

    public void setCorIdCompResultado(String corIdCompResultado) {
        this.corIdCompResultado = corIdCompResultado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_fecha", length=22)
    public Date getComFecha() {
        return this.comFecha;
    }

    public void setComFecha(Date comFecha) {
        this.comFecha = comFecha;
    }


    @Column(name="com_observacion", length=1000)
    public String getComObservacion() {
        return this.comObservacion;
    }

    public void setComObservacion(String comObservacion) {
        this.comObservacion = comObservacion;
    }


    @Column(name="coe_id_comp_estado", length=3)
    public String getCoeIdCompEstado() {
        return this.coeIdCompEstado;
    }

    public void setCoeIdCompEstado(String coeIdCompEstado) {
        this.coeIdCompEstado = coeIdCompEstado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_dt_end", length=22)
    public Date getComDtEnd() {
        return this.comDtEnd;
    }

    public void setComDtEnd(Date comDtEnd) {
        this.comDtEnd = comDtEnd;
    }


    @Column(name="com_responsable", length=30)
    public String getComResponsable() {
        return this.comResponsable;
    }

    public void setComResponsable(String comResponsable) {
        this.comResponsable = comResponsable;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_dt_inicio", length=22)
    public Date getComDtInicio() {
        return this.comDtInicio;
    }

    public void setComDtInicio(Date comDtInicio) {
        this.comDtInicio = comDtInicio;
    }


    @Column(name="com_actuacion", length=1000)
    public String getComActuacion() {
        return this.comActuacion;
    }

    public void setComActuacion(String comActuacion) {
        this.comActuacion = comActuacion;
    }


    @Column(name="com_notas", length=254)
    public String getComNotas() {
        return this.comNotas;
    }

    public void setComNotas(String comNotas) {
        this.comNotas = comNotas;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_dt_inicio_termino", length=22)
    public Date getComDtInicioTermino() {
        return this.comDtInicioTermino;
    }

    public void setComDtInicioTermino(Date comDtInicioTermino) {
        this.comDtInicioTermino = comDtInicioTermino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_dt_fin_termino", length=22)
    public Date getComDtFinTermino() {
        return this.comDtFinTermino;
    }

    public void setComDtFinTermino(Date comDtFinTermino) {
        this.comDtFinTermino = comDtFinTermino;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="com_dt_registro", length=22)
    public Date getComDtRegistro() {
        return this.comDtRegistro;
    }

    public void setComDtRegistro(Date comDtRegistro) {
        this.comDtRegistro = comDtRegistro;
    }


    @Column(name="com_url_documento", length=1000)
    public String getComUrlDocumento() {
        return this.comUrlDocumento;
    }

    public void setComUrlDocumento(String comUrlDocumento) {
        this.comUrlDocumento = comUrlDocumento;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="com_nm_documento", length=2000)
    public String getComNmDocumento() {
        return this.comNmDocumento;
    }

    public void setComNmDocumento(String comNmDocumento) {
        this.comNmDocumento = comNmDocumento;
    }


    @Column(name="com_secuencial")
    public Long getComSecuencial() {
        return this.comSecuencial;
    }

    public void setComSecuencial(Long comSecuencial) {
        this.comSecuencial = comSecuencial;
    }




}


