package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:10:33 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpRolesId generated by hbm2java
 */
@Embeddable
public class M4sllTpRolesId  implements java.io.Serializable {


    private long tprIdTpRol;
    private String idOrganization;

    public M4sllTpRolesId() {
    }

    public M4sllTpRolesId(long tprIdTpRol, String idOrganization) {
        this.tprIdTpRol = tprIdTpRol;
        this.idOrganization = idOrganization;
    }



    @Column(name="tpr_id_tp_rol", nullable=false)
    public long getTprIdTpRol() {
        return this.tprIdTpRol;
    }

    public void setTprIdTpRol(long tprIdTpRol) {
        this.tprIdTpRol = tprIdTpRol;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpRolesId) ) return false;
        M4sllTpRolesId castOther = ( M4sllTpRolesId ) other;

        return (this.getTprIdTpRol()==castOther.getTprIdTpRol())
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getTprIdTpRol();
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


