package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpAutorReuId generated by hbm2java
 */
@Embeddable
public class M4sllTpAutorReuId  implements java.io.Serializable {


    private String tarIdTpAutorReu;
    private String idOrganization;

    public M4sllTpAutorReuId() {
    }

    public M4sllTpAutorReuId(String tarIdTpAutorReu, String idOrganization) {
        this.tarIdTpAutorReu = tarIdTpAutorReu;
        this.idOrganization = idOrganization;
    }



    @Column(name="tar_id_tp_autor_reu", nullable=false, length=3)
    public String getTarIdTpAutorReu() {
        return this.tarIdTpAutorReu;
    }

    public void setTarIdTpAutorReu(String tarIdTpAutorReu) {
        this.tarIdTpAutorReu = tarIdTpAutorReu;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpAutorReuId) ) return false;
        M4sllTpAutorReuId castOther = ( M4sllTpAutorReuId ) other;

        return ( (this.getTarIdTpAutorReu()==castOther.getTarIdTpAutorReu()) || ( this.getTarIdTpAutorReu()!=null && castOther.getTarIdTpAutorReu()!=null && this.getTarIdTpAutorReu().equals(castOther.getTarIdTpAutorReu()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTarIdTpAutorReu() == null ? 0 : this.getTarIdTpAutorReu().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


