package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpMotivoId generated by hbm2java
 */
@Embeddable
public class M4sllTpMotivoId  implements java.io.Serializable {


    private String tmoIdTpMotivo;
    private String idOrganization;

    public M4sllTpMotivoId() {
    }

    public M4sllTpMotivoId(String tmoIdTpMotivo, String idOrganization) {
        this.tmoIdTpMotivo = tmoIdTpMotivo;
        this.idOrganization = idOrganization;
    }



    @Column(name="tmo_id_tp_motivo", nullable=false, length=3)
    public String getTmoIdTpMotivo() {
        return this.tmoIdTpMotivo;
    }

    public void setTmoIdTpMotivo(String tmoIdTpMotivo) {
        this.tmoIdTpMotivo = tmoIdTpMotivo;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpMotivoId) ) return false;
        M4sllTpMotivoId castOther = ( M4sllTpMotivoId ) other;

        return ( (this.getTmoIdTpMotivo()==castOther.getTmoIdTpMotivo()) || ( this.getTmoIdTpMotivo()!=null && castOther.getTmoIdTpMotivo()!=null && this.getTmoIdTpMotivo().equals(castOther.getTmoIdTpMotivo()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTmoIdTpMotivo() == null ? 0 : this.getTmoIdTpMotivo().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


