package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpStaDet generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_sta_det"
            ,schema="sll"
      )
public class M4sllTpStaDet  implements java.io.Serializable {


    private M4sllTpStaDetId id;
    private String tsdNmTpStatusDet;
    private String tplIdTpLitigio;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tsdDtStart;
    private Date tsdDtEnd;

    public M4sllTpStaDet() {
    }


    public M4sllTpStaDet(M4sllTpStaDetId id) {
        this.id = id;
    }
    public M4sllTpStaDet(M4sllTpStaDetId id, String tsdNmTpStatusDet, String tplIdTpLitigio, String idApprole, String idSecuser, Date dtLastUpdate, Date tsdDtStart, Date tsdDtEnd) {
        this.id = id;
        this.tsdNmTpStatusDet = tsdNmTpStatusDet;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tsdDtStart = tsdDtStart;
        this.tsdDtEnd = tsdDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tsdIdTpStaDet", column=@Column(name="tsd_id_tp_sta_det", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpStaDetId getId() {
        return this.id;
    }

    public void setId(M4sllTpStaDetId id) {
        this.id = id;
    }


    @Column(name="tsd_nm_tp_status_det", length=254)
    public String getTsdNmTpStatusDet() {
        return this.tsdNmTpStatusDet;
    }

    public void setTsdNmTpStatusDet(String tsdNmTpStatusDet) {
        this.tsdNmTpStatusDet = tsdNmTpStatusDet;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tsd_dt_start", length=22)
    public Date getTsdDtStart() {
        return this.tsdDtStart;
    }

    public void setTsdDtStart(Date tsdDtStart) {
        this.tsdDtStart = tsdDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tsd_dt_end", length=22)
    public Date getTsdDtEnd() {
        return this.tsdDtEnd;
    }

    public void setTsdDtEnd(Date tsdDtEnd) {
        this.tsdDtEnd = tsdDtEnd;
    }




}


