package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllCpeCejpjDId generated by hbm2java
 */
@Embeddable
public class M4sllCpeCejpjDId  implements java.io.Serializable {


    private String litIdLitigio;
    private long ccdIdSecuencia;
    private String idOrganization;

    public M4sllCpeCejpjDId() {
    }

    public M4sllCpeCejpjDId(String litIdLitigio, long ccdIdSecuencia, String idOrganization) {
        this.litIdLitigio = litIdLitigio;
        this.ccdIdSecuencia = ccdIdSecuencia;
        this.idOrganization = idOrganization;
    }



    @Column(name="lit_id_litigio", nullable=false, length=10)
    public String getLitIdLitigio() {
        return this.litIdLitigio;
    }

    public void setLitIdLitigio(String litIdLitigio) {
        this.litIdLitigio = litIdLitigio;
    }


    @Column(name="ccd_id_secuencia", nullable=false)
    public long getCcdIdSecuencia() {
        return this.ccdIdSecuencia;
    }

    public void setCcdIdSecuencia(long ccdIdSecuencia) {
        this.ccdIdSecuencia = ccdIdSecuencia;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllCpeCejpjDId) ) return false;
        M4sllCpeCejpjDId castOther = ( M4sllCpeCejpjDId ) other;

        return ( (this.getLitIdLitigio()==castOther.getLitIdLitigio()) || ( this.getLitIdLitigio()!=null && castOther.getLitIdLitigio()!=null && this.getLitIdLitigio().equals(castOther.getLitIdLitigio()) ) )
               && (this.getCcdIdSecuencia()==castOther.getCcdIdSecuencia())
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getLitIdLitigio() == null ? 0 : this.getLitIdLitigio().hashCode() );
        result = 37 * result + (int) this.getCcdIdSecuencia();
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


