package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpStatusId generated by hbm2java
 */
@Embeddable
public class M4sllTpStatusId  implements java.io.Serializable {


    private String tstIdTpStatus;
    private String idOrganization;

    public M4sllTpStatusId() {
    }

    public M4sllTpStatusId(String tstIdTpStatus, String idOrganization) {
        this.tstIdTpStatus = tstIdTpStatus;
        this.idOrganization = idOrganization;
    }



    @Column(name="tst_id_tp_status", nullable=false, length=3)
    public String getTstIdTpStatus() {
        return this.tstIdTpStatus;
    }

    public void setTstIdTpStatus(String tstIdTpStatus) {
        this.tstIdTpStatus = tstIdTpStatus;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpStatusId) ) return false;
        M4sllTpStatusId castOther = ( M4sllTpStatusId ) other;

        return ( (this.getTstIdTpStatus()==castOther.getTstIdTpStatus()) || ( this.getTstIdTpStatus()!=null && castOther.getTstIdTpStatus()!=null && this.getTstIdTpStatus().equals(castOther.getTstIdTpStatus()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTstIdTpStatus() == null ? 0 : this.getTstIdTpStatus().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


