package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpAutorReu generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_autor_reu"
            ,schema="sll"
      )
public class M4sllTpAutorReu  implements java.io.Serializable {


    private M4sllTpAutorReuId id;
    private String tarNmTpAutorReu;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tarDtStart;
    private Date tarDtEnd;

    public M4sllTpAutorReu() {
    }


    public M4sllTpAutorReu(M4sllTpAutorReuId id) {
        this.id = id;
    }
    public M4sllTpAutorReu(M4sllTpAutorReuId id, String tarNmTpAutorReu, String idApprole, String idSecuser, Date dtLastUpdate, Date tarDtStart, Date tarDtEnd) {
        this.id = id;
        this.tarNmTpAutorReu = tarNmTpAutorReu;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tarDtStart = tarDtStart;
        this.tarDtEnd = tarDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tarIdTpAutorReu", column=@Column(name="tar_id_tp_autor_reu", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpAutorReuId getId() {
        return this.id;
    }

    public void setId(M4sllTpAutorReuId id) {
        this.id = id;
    }


    @Column(name="tar_nm_tp_autor_reu", length=254)
    public String getTarNmTpAutorReu() {
        return this.tarNmTpAutorReu;
    }

    public void setTarNmTpAutorReu(String tarNmTpAutorReu) {
        this.tarNmTpAutorReu = tarNmTpAutorReu;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tar_dt_start", length=22)
    public Date getTarDtStart() {
        return this.tarDtStart;
    }

    public void setTarDtStart(Date tarDtStart) {
        this.tarDtStart = tarDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tar_dt_end", length=22)
    public Date getTarDtEnd() {
        return this.tarDtEnd;
    }

    public void setTarDtEnd(Date tarDtEnd) {
        this.tarDtEnd = tarDtEnd;
    }




}


