package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:07:32 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllMtoRiesgos generated by hbm2java
 */
@Entity
@Table(name="m4sll_mto_riesgos"
            ,schema="sll"
      )
public class M4sllMtoRiesgos  implements java.io.Serializable {


    private M4sllMtoRiesgosId id;
    private String mriNmRiesgo;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date mriDtStart;
    private Date mriDtEnd;

    public M4sllMtoRiesgos() {
    }


    public M4sllMtoRiesgos(M4sllMtoRiesgosId id) {
        this.id = id;
    }
    public M4sllMtoRiesgos(M4sllMtoRiesgosId id, String mriNmRiesgo, String idApprole, String idSecuser, Date dtLastUpdate, Date mriDtStart, Date mriDtEnd) {
        this.id = id;
        this.mriNmRiesgo = mriNmRiesgo;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.mriDtStart = mriDtStart;
        this.mriDtEnd = mriDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="mriIdRiesgo", column=@Column(name="mri_id_riesgo", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllMtoRiesgosId getId() {
        return this.id;
    }

    public void setId(M4sllMtoRiesgosId id) {
        this.id = id;
    }


    @Column(name="mri_nm_riesgo", length=254)
    public String getMriNmRiesgo() {
        return this.mriNmRiesgo;
    }

    public void setMriNmRiesgo(String mriNmRiesgo) {
        this.mriNmRiesgo = mriNmRiesgo;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="mri_dt_start", length=22)
    public Date getMriDtStart() {
        return this.mriDtStart;
    }

    public void setMriDtStart(Date mriDtStart) {
        this.mriDtStart = mriDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="mri_dt_end", length=22)
    public Date getMriDtEnd() {
        return this.mriDtEnd;
    }

    public void setMriDtEnd(Date mriDtEnd) {
        this.mriDtEnd = mriDtEnd;
    }




}


