package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:08:16 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTribunalesId generated by hbm2java
 */
@Embeddable
public class M4sllTribunalesId  implements java.io.Serializable {


    private String triIdTribunal;
    private String idOrganization;

    public M4sllTribunalesId() {
    }

    public M4sllTribunalesId(String triIdTribunal, String idOrganization) {
        this.triIdTribunal = triIdTribunal;
        this.idOrganization = idOrganization;
    }



    @Column(name="tri_id_tribunal", nullable=false, length=3)
    public String getTriIdTribunal() {
        return this.triIdTribunal;
    }

    public void setTriIdTribunal(String triIdTribunal) {
        this.triIdTribunal = triIdTribunal;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTribunalesId) ) return false;
        M4sllTribunalesId castOther = ( M4sllTribunalesId ) other;

        return ( (this.getTriIdTribunal()==castOther.getTriIdTribunal()) || ( this.getTriIdTribunal()!=null && castOther.getTriIdTribunal()!=null && this.getTriIdTribunal().equals(castOther.getTriIdTribunal()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTriIdTribunal() == null ? 0 : this.getTriIdTribunal().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


