package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpPedido generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_pedido"
            ,schema="sll"
      )
public class M4sllTpPedido  implements java.io.Serializable {


    private M4sllTpPedidoId id;
    private String tpeNmPedido;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String tplIdTpLitigio;
    private String tpeProvisionaSN;
    private Date tpeDtEnd;
    private Date tpeDtStart;

    public M4sllTpPedido() {
    }


    public M4sllTpPedido(M4sllTpPedidoId id) {
        this.id = id;
    }
    public M4sllTpPedido(M4sllTpPedidoId id, String tpeNmPedido, String idApprole, String idSecuser, Date dtLastUpdate, String tplIdTpLitigio, String tpeProvisionaSN, Date tpeDtEnd, Date tpeDtStart) {
        this.id = id;
        this.tpeNmPedido = tpeNmPedido;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.tpeProvisionaSN = tpeProvisionaSN;
        this.tpeDtEnd = tpeDtEnd;
        this.tpeDtStart = tpeDtStart;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tpeIdPedido", column=@Column(name="tpe_id_pedido", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpPedidoId getId() {
        return this.id;
    }

    public void setId(M4sllTpPedidoId id) {
        this.id = id;
    }


    @Column(name="tpe_nm_pedido", length=254)
    public String getTpeNmPedido() {
        return this.tpeNmPedido;
    }

    public void setTpeNmPedido(String tpeNmPedido) {
        this.tpeNmPedido = tpeNmPedido;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="tpe_provisiona_s_n", length=1)
    public String getTpeProvisionaSN() {
        return this.tpeProvisionaSN;
    }

    public void setTpeProvisionaSN(String tpeProvisionaSN) {
        this.tpeProvisionaSN = tpeProvisionaSN;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpe_dt_end", length=22)
    public Date getTpeDtEnd() {
        return this.tpeDtEnd;
    }

    public void setTpeDtEnd(Date tpeDtEnd) {
        this.tpeDtEnd = tpeDtEnd;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpe_dt_start", length=22)
    public Date getTpeDtStart() {
        return this.tpeDtStart;
    }

    public void setTpeDtStart(Date tpeDtStart) {
        this.tpeDtStart = tpeDtStart;
    }




}


