package com.prosegur.sllpe.domain;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllAutorReu generated by hbm2java
 */
@Entity
@Table(name="m4sll_autor_reu"
            ,schema="sll"
      )
public class M4sllAutorReu  implements java.io.Serializable {


    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private M4sllAutorReuId id;
    private Long stdOrHrPeriod;
    private Long mabSecuencia;
    private String mteIdTpEmpleado;
    private String tarIdTpAutorReu;
    private String aurAutorReu;
    private String tpiIdTpIdentificacion;
    private String entNroIdentificacion;
    private String pexNroDocumento;
    private String stdIdLegEnt;
    private String stdIdPerson;
    private String aurEmail;
    private String aurNombreAbogado;
    private BigDecimal aurTelefono;
    private String aurObservaciones;
    private String aurCkPrincipal;
    private String tpeIdTpEntidad;
    private String aurCkSubsidiario;
    private String aurCkSolidario;
    private BigDecimal aurMontoIndemnizacion;
    private String aurCausaDesvinculacion;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String eciIdCiudad;

    public M4sllAutorReu() {
    }


    public M4sllAutorReu(M4sllAutorReuId id) {
        this.id = id;
    }
    public M4sllAutorReu(M4sllAutorReuId id, Long stdOrHrPeriod, Long mabSecuencia, String mteIdTpEmpleado, String tarIdTpAutorReu, String aurAutorReu, String tpiIdTpIdentificacion, String entNroIdentificacion, String pexNroDocumento, String stdIdLegEnt, String stdIdPerson, String aurEmail, String aurNombreAbogado, BigDecimal aurTelefono, String aurObservaciones, String aurCkPrincipal, String tpeIdTpEntidad, String aurCkSubsidiario, String aurCkSolidario, BigDecimal aurMontoIndemnizacion, String aurCausaDesvinculacion, String idApprole, String idSecuser, Date dtLastUpdate, String eciIdCiudad) {
        this.id = id;
        this.stdOrHrPeriod = stdOrHrPeriod;
        this.mabSecuencia = mabSecuencia;
        this.mteIdTpEmpleado = mteIdTpEmpleado;
        this.tarIdTpAutorReu = tarIdTpAutorReu;
        this.aurAutorReu = aurAutorReu;
        this.tpiIdTpIdentificacion = tpiIdTpIdentificacion;
        this.entNroIdentificacion = entNroIdentificacion;
        this.pexNroDocumento = pexNroDocumento;
        this.stdIdLegEnt = stdIdLegEnt;
        this.stdIdPerson = stdIdPerson;
        this.aurEmail = aurEmail;
        this.aurNombreAbogado = aurNombreAbogado;
        this.aurTelefono = aurTelefono;
        this.aurObservaciones = aurObservaciones;
        this.aurCkPrincipal = aurCkPrincipal;
        this.tpeIdTpEntidad = tpeIdTpEntidad;
        this.aurCkSubsidiario = aurCkSubsidiario;
        this.aurCkSolidario = aurCkSolidario;
        this.aurMontoIndemnizacion = aurMontoIndemnizacion;
        this.aurCausaDesvinculacion = aurCausaDesvinculacion;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.eciIdCiudad = eciIdCiudad;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="aurSecuencia", column=@Column(name="aur_secuencia", nullable=false) ),
        @AttributeOverride(name="litIdLitigio", column=@Column(name="lit_id_litigio", nullable=false, length=10) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllAutorReuId getId() {
        return this.id;
    }

    public void setId(M4sllAutorReuId id) {
        this.id = id;
    }


    @Column(name="std_or_hr_period")
    public Long getStdOrHrPeriod() {
        return this.stdOrHrPeriod;
    }

    public void setStdOrHrPeriod(Long stdOrHrPeriod) {
        this.stdOrHrPeriod = stdOrHrPeriod;
    }


    @Column(name="mab_secuencia")
    public Long getMabSecuencia() {
        return this.mabSecuencia;
    }

    public void setMabSecuencia(Long mabSecuencia) {
        this.mabSecuencia = mabSecuencia;
    }


    @Column(name="mte_id_tp_empleado", length=3)
    public String getMteIdTpEmpleado() {
        return this.mteIdTpEmpleado;
    }

    public void setMteIdTpEmpleado(String mteIdTpEmpleado) {
        this.mteIdTpEmpleado = mteIdTpEmpleado;
    }


    @Column(name="tar_id_tp_autor_reu", length=3)
    public String getTarIdTpAutorReu() {
        return this.tarIdTpAutorReu;
    }

    public void setTarIdTpAutorReu(String tarIdTpAutorReu) {
        this.tarIdTpAutorReu = tarIdTpAutorReu;
    }


    @Column(name="aur_autor_reu", length=1)
    public String getAurAutorReu() {
        return this.aurAutorReu;
    }

    public void setAurAutorReu(String aurAutorReu) {
        this.aurAutorReu = aurAutorReu;
    }


    @Column(name="tpi_id_tp_identificacion", length=3)
    public String getTpiIdTpIdentificacion() {
        return this.tpiIdTpIdentificacion;
    }

    public void setTpiIdTpIdentificacion(String tpiIdTpIdentificacion) {
        this.tpiIdTpIdentificacion = tpiIdTpIdentificacion;
    }


    @Column(name="ent_nro_identificacion", length=254)
    public String getEntNroIdentificacion() {
        return this.entNroIdentificacion;
    }

    public void setEntNroIdentificacion(String entNroIdentificacion) {
        this.entNroIdentificacion = entNroIdentificacion;
    }


    @Column(name="pex_nro_documento", length=20)
    public String getPexNroDocumento() {
        return this.pexNroDocumento;
    }

    public void setPexNroDocumento(String pexNroDocumento) {
        this.pexNroDocumento = pexNroDocumento;
    }


    @Column(name="std_id_leg_ent", length=9)
    public String getStdIdLegEnt() {
        return this.stdIdLegEnt;
    }

    public void setStdIdLegEnt(String stdIdLegEnt) {
        this.stdIdLegEnt = stdIdLegEnt;
    }


    @Column(name="std_id_person", length=10)
    public String getStdIdPerson() {
        return this.stdIdPerson;
    }

    public void setStdIdPerson(String stdIdPerson) {
        this.stdIdPerson = stdIdPerson;
    }


    @Column(name="aur_email", length=1000)
    public String getAurEmail() {
        return this.aurEmail;
    }

    public void setAurEmail(String aurEmail) {
        this.aurEmail = aurEmail;
    }


    @Column(name="aur_nombre_abogado", length=1000)
    public String getAurNombreAbogado() {
        return this.aurNombreAbogado;
    }

    public void setAurNombreAbogado(String aurNombreAbogado) {
        this.aurNombreAbogado = aurNombreAbogado;
    }


    @Column(name="aur_telefono", precision=18, scale=4)
    public BigDecimal getAurTelefono() {
        return this.aurTelefono;
    }

    public void setAurTelefono(BigDecimal aurTelefono) {
        this.aurTelefono = aurTelefono;
    }


    @Column(name="aur_observaciones", length=1000)
    public String getAurObservaciones() {
        return this.aurObservaciones;
    }

    public void setAurObservaciones(String aurObservaciones) {
        this.aurObservaciones = aurObservaciones;
    }


    @Column(name="aur_ck_principal", length=1)
    public String getAurCkPrincipal() {
        return this.aurCkPrincipal;
    }

    public void setAurCkPrincipal(String aurCkPrincipal) {
        this.aurCkPrincipal = aurCkPrincipal;
    }


    @Column(name="tpe_id_tp_entidad", length=3)
    public String getTpeIdTpEntidad() {
        return this.tpeIdTpEntidad;
    }

    public void setTpeIdTpEntidad(String tpeIdTpEntidad) {
        this.tpeIdTpEntidad = tpeIdTpEntidad;
    }


    @Column(name="aur_ck_subsidiario", length=1)
    public String getAurCkSubsidiario() {
        return this.aurCkSubsidiario;
    }

    public void setAurCkSubsidiario(String aurCkSubsidiario) {
        this.aurCkSubsidiario = aurCkSubsidiario;
    }


    @Column(name="aur_ck_solidario", length=1)
    public String getAurCkSolidario() {
        return this.aurCkSolidario;
    }

    public void setAurCkSolidario(String aurCkSolidario) {
        this.aurCkSolidario = aurCkSolidario;
    }


    @Column(name="aur_monto_indemnizacion", precision=14, scale=4)
    public BigDecimal getAurMontoIndemnizacion() {
        return this.aurMontoIndemnizacion;
    }

    public void setAurMontoIndemnizacion(BigDecimal aurMontoIndemnizacion) {
        this.aurMontoIndemnizacion = aurMontoIndemnizacion;
    }


    @Column(name="aur_causa_desvinculacion", length=254)
    public String getAurCausaDesvinculacion() {
        return this.aurCausaDesvinculacion;
    }

    public void setAurCausaDesvinculacion(String aurCausaDesvinculacion) {
        this.aurCausaDesvinculacion = aurCausaDesvinculacion;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="eci_id_ciudad", length=3)
    public String getEciIdCiudad() {
        return this.eciIdCiudad;
    }

    public void setEciIdCiudad(String eciIdCiudad) {
        this.eciIdCiudad = eciIdCiudad;
    }




}


