package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:10:17 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpRecurren generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_recurren"
            ,schema="sll"
      )
public class M4sllTpRecurren  implements java.io.Serializable {


    private M4sllTpRecurrenId id;
    private String treNmRecurrencia;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date treDtStart;
    private Date treDtEnd;

    public M4sllTpRecurren() {
    }


    public M4sllTpRecurren(M4sllTpRecurrenId id) {
        this.id = id;
    }
    public M4sllTpRecurren(M4sllTpRecurrenId id, String treNmRecurrencia, String idApprole, String idSecuser, Date dtLastUpdate, Date treDtStart, Date treDtEnd) {
        this.id = id;
        this.treNmRecurrencia = treNmRecurrencia;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.treDtStart = treDtStart;
        this.treDtEnd = treDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="treIdRecurrencia", column=@Column(name="tre_id_recurrencia", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpRecurrenId getId() {
        return this.id;
    }

    public void setId(M4sllTpRecurrenId id) {
        this.id = id;
    }


    @Column(name="tre_nm_recurrencia", length=254)
    public String getTreNmRecurrencia() {
        return this.treNmRecurrencia;
    }

    public void setTreNmRecurrencia(String treNmRecurrencia) {
        this.treNmRecurrencia = treNmRecurrencia;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tre_dt_start", length=22)
    public Date getTreDtStart() {
        return this.treDtStart;
    }

    public void setTreDtStart(Date treDtStart) {
        this.treDtStart = treDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tre_dt_end", length=22)
    public Date getTreDtEnd() {
        return this.treDtEnd;
    }

    public void setTreDtEnd(Date treDtEnd) {
        this.treDtEnd = treDtEnd;
    }




}


