package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:08:33 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpCompromis generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_compromis"
            ,schema="sll"
      )
public class M4sllTpCompromis  implements java.io.Serializable {


    private M4sllTpCompromisId id;
    private String tplIdTpLitigio;
    private String tcoNmTpCompromiso;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Short tcoDtValidez;
    private Date tcoDtStart;
    private Date tcoDtEnd;

    public M4sllTpCompromis() {
    }


    public M4sllTpCompromis(M4sllTpCompromisId id) {
        this.id = id;
    }
    public M4sllTpCompromis(M4sllTpCompromisId id, String tplIdTpLitigio, String tcoNmTpCompromiso, String idApprole, String idSecuser, Date dtLastUpdate, Short tcoDtValidez, Date tcoDtStart, Date tcoDtEnd) {
        this.id = id;
        this.tplIdTpLitigio = tplIdTpLitigio;
        this.tcoNmTpCompromiso = tcoNmTpCompromiso;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tcoDtValidez = tcoDtValidez;
        this.tcoDtStart = tcoDtStart;
        this.tcoDtEnd = tcoDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tcoIdTpCompromiso", column=@Column(name="tco_id_tp_compromiso", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpCompromisId getId() {
        return this.id;
    }

    public void setId(M4sllTpCompromisId id) {
        this.id = id;
    }


    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }

    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }


    @Column(name="tco_nm_tp_compromiso", length=254)
    public String getTcoNmTpCompromiso() {
        return this.tcoNmTpCompromiso;
    }

    public void setTcoNmTpCompromiso(String tcoNmTpCompromiso) {
        this.tcoNmTpCompromiso = tcoNmTpCompromiso;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="tco_dt_validez")
    public Short getTcoDtValidez() {
        return this.tcoDtValidez;
    }

    public void setTcoDtValidez(Short tcoDtValidez) {
        this.tcoDtValidez = tcoDtValidez;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tco_dt_start", length=22)
    public Date getTcoDtStart() {
        return this.tcoDtStart;
    }

    public void setTcoDtStart(Date tcoDtStart) {
        this.tcoDtStart = tcoDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tco_dt_end", length=22)
    public Date getTcoDtEnd() {
        return this.tcoDtEnd;
    }

    public void setTcoDtEnd(Date tcoDtEnd) {
        this.tcoDtEnd = tcoDtEnd;
    }




}


