package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpIdentific generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_identific"
            ,schema="sll"
      )
public class M4sllTpIdentific  implements java.io.Serializable {


    private M4sllTpIdentificId id;
    private String tpiNmTpIdentificacion;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Date tpiDtStart;
    private Date tpiDtEnd;

    public M4sllTpIdentific() {
    }


    public M4sllTpIdentific(M4sllTpIdentificId id) {
        this.id = id;
    }
    public M4sllTpIdentific(M4sllTpIdentificId id, String tpiNmTpIdentificacion, String idApprole, String idSecuser, Date dtLastUpdate, Date tpiDtStart, Date tpiDtEnd) {
        this.id = id;
        this.tpiNmTpIdentificacion = tpiNmTpIdentificacion;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.tpiDtStart = tpiDtStart;
        this.tpiDtEnd = tpiDtEnd;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="tpiIdTpIdentificacion", column=@Column(name="tpi_id_tp_identificacion", nullable=false, length=3) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllTpIdentificId getId() {
        return this.id;
    }

    public void setId(M4sllTpIdentificId id) {
        this.id = id;
    }


    @Column(name="tpi_nm_tp_identificacion", length=254)
    public String getTpiNmTpIdentificacion() {
        return this.tpiNmTpIdentificacion;
    }

    public void setTpiNmTpIdentificacion(String tpiNmTpIdentificacion) {
        this.tpiNmTpIdentificacion = tpiNmTpIdentificacion;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpi_dt_start", length=22)
    public Date getTpiDtStart() {
        return this.tpiDtStart;
    }

    public void setTpiDtStart(Date tpiDtStart) {
        this.tpiDtStart = tpiDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpi_dt_end", length=22)
    public Date getTpiDtEnd() {
        return this.tpiDtEnd;
    }

    public void setTpiDtEnd(Date tpiDtEnd) {
        this.tpiDtEnd = tpiDtEnd;
    }




}


