package com.prosegur.sllpe.domain;
// Generated Mar 24, 2021, 12:01:42 PM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllDocLitigiosId generated by hbm2java
 */
@Embeddable
public class M4sllDocLitigiosId  implements java.io.Serializable {


     private long dolSecuencia;
     private String litIdLitigio;
     private String idOrganization;

    public M4sllDocLitigiosId() {
    }

    public M4sllDocLitigiosId(long dolSecuencia, String litIdLitigio, String idOrganization) {
       this.dolSecuencia = dolSecuencia;
       this.litIdLitigio = litIdLitigio;
       this.idOrganization = idOrganization;
    }
   


    @Column(name="dol_secuencia", nullable=false)
    public long getDolSecuencia() {
        return this.dolSecuencia;
    }
    
    public void setDolSecuencia(long dolSecuencia) {
        this.dolSecuencia = dolSecuencia;
    }


    @Column(name="lit_id_litigio", nullable=false, length=10)
    public String getLitIdLitigio() {
        return this.litIdLitigio;
    }
    
    public void setLitIdLitigio(String litIdLitigio) {
        this.litIdLitigio = litIdLitigio;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }
    
    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof M4sllDocLitigiosId) ) return false;
		 M4sllDocLitigiosId castOther = ( M4sllDocLitigiosId ) other; 
         
		 return (this.getDolSecuencia()==castOther.getDolSecuencia())
 && ( (this.getLitIdLitigio()==castOther.getLitIdLitigio()) || ( this.getLitIdLitigio()!=null && castOther.getLitIdLitigio()!=null && this.getLitIdLitigio().equals(castOther.getLitIdLitigio()) ) )
 && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getDolSecuencia();
         result = 37 * result + ( getLitIdLitigio() == null ? 0 : this.getLitIdLitigio().hashCode() );
         result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
         return result;
   }   


}


