package com.prosegur.sllpe.domain;
// Generated Mar 29, 2021, 11:30:20 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllTpEntidades generated by hbm2java
 */
@Entity
@Table(name="m4sll_tp_entidades"
    ,schema="sll"
)
public class M4sllTpEntidades  implements java.io.Serializable {


     private M4sllTpEntidadesId id;
     private String tpeNmTpEntidad;
     private String idApprole;
     private String idSecuser;
     private Date dtLastUpdate;
     private String tplIdTpLitigio;
     private Date tpeDtStart;
     private Date tpeDtEnd;

    public M4sllTpEntidades() {
    }

	
    public M4sllTpEntidades(M4sllTpEntidadesId id) {
        this.id = id;
    }
    public M4sllTpEntidades(M4sllTpEntidadesId id, String tpeNmTpEntidad, String idApprole, String idSecuser, Date dtLastUpdate, String tplIdTpLitigio, Date tpeDtStart, Date tpeDtEnd) {
       this.id = id;
       this.tpeNmTpEntidad = tpeNmTpEntidad;
       this.idApprole = idApprole;
       this.idSecuser = idSecuser;
       this.dtLastUpdate = dtLastUpdate;
       this.tplIdTpLitigio = tplIdTpLitigio;
       this.tpeDtStart = tpeDtStart;
       this.tpeDtEnd = tpeDtEnd;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="tpeIdTpEntidad", column=@Column(name="tpe_id_tp_entidad", nullable=false, length=3) ), 
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) ) } )
    public M4sllTpEntidadesId getId() {
        return this.id;
    }
    
    public void setId(M4sllTpEntidadesId id) {
        this.id = id;
    }

    
    @Column(name="tpe_nm_tp_entidad", length=254)
    public String getTpeNmTpEntidad() {
        return this.tpeNmTpEntidad;
    }
    
    public void setTpeNmTpEntidad(String tpeNmTpEntidad) {
        this.tpeNmTpEntidad = tpeNmTpEntidad;
    }

    
    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }
    
    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }

    
    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }
    
    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }
    
    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }

    
    @Column(name="tpl_id_tp_litigio", length=3)
    public String getTplIdTpLitigio() {
        return this.tplIdTpLitigio;
    }
    
    public void setTplIdTpLitigio(String tplIdTpLitigio) {
        this.tplIdTpLitigio = tplIdTpLitigio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpe_dt_start", length=22)
    public Date getTpeDtStart() {
        return this.tpeDtStart;
    }
    
    public void setTpeDtStart(Date tpeDtStart) {
        this.tpeDtStart = tpeDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tpe_dt_end", length=22)
    public Date getTpeDtEnd() {
        return this.tpeDtEnd;
    }
    
    public void setTpeDtEnd(Date tpeDtEnd) {
        this.tpeDtEnd = tpeDtEnd;
    }




}


