package com.prosegur.sllpe.domain;
// Generated 22 mar. 2021 12:06:28 by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllAutorReuId generated by hbm2java
 */
@Embeddable
public class M4sllAutorReuId  implements java.io.Serializable {


    private long aurSecuencia;
    private String litIdLitigio;
    private String idOrganization;

    public M4sllAutorReuId() {
    }

    public M4sllAutorReuId(long aurSecuencia, String litIdLitigio, String idOrganization) {
        this.aurSecuencia = aurSecuencia;
        this.litIdLitigio = litIdLitigio;
        this.idOrganization = idOrganization;
    }



    @Column(name="aur_secuencia", nullable=false)
    public long getAurSecuencia() {
        return this.aurSecuencia;
    }

    public void setAurSecuencia(long aurSecuencia) {
        this.aurSecuencia = aurSecuencia;
    }


    @Column(name="lit_id_litigio", nullable=false, length=10)
    public String getLitIdLitigio() {
        return this.litIdLitigio;
    }

    public void setLitIdLitigio(String litIdLitigio) {
        this.litIdLitigio = litIdLitigio;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllAutorReuId) ) return false;
        M4sllAutorReuId castOther = ( M4sllAutorReuId ) other;

        return (this.getAurSecuencia()==castOther.getAurSecuencia())
               && ( (this.getLitIdLitigio()==castOther.getLitIdLitigio()) || ( this.getLitIdLitigio()!=null && castOther.getLitIdLitigio()!=null && this.getLitIdLitigio().equals(castOther.getLitIdLitigio()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (int) this.getAurSecuencia();
        result = 37 * result + ( getLitIdLitigio() == null ? 0 : this.getLitIdLitigio().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


