package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sllCpeCejpjC generated by hbm2java
 */
@Entity
@Table(name="m4sll_cpe_cejpj_c"
            ,schema="sll"
      )
public class M4sllCpeCejpjC  implements java.io.Serializable {


    private M4sllCpeCejpjCId id;
    private String fasNroRadicacion;
    private String cccDemandante;
    private String cccDemandado;
    private String cccOrgano;
    private String cccDistrito;
    private String cccJuez;
    private Date cccFechaInicio;
    private String cccProceso;
    private String cccEspecialidad;
    private String cccMateria;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;

    public M4sllCpeCejpjC() {
    }


    public M4sllCpeCejpjC(M4sllCpeCejpjCId id) {
        this.id = id;
    }
    public M4sllCpeCejpjC(M4sllCpeCejpjCId id, String fasNroRadicacion, String cccDemandante, String cccDemandado, String cccOrgano, String cccDistrito, String cccJuez, Date cccFechaInicio, String cccProceso, String cccEspecialidad, String cccMateria, String idApprole, String idSecuser, Date dtLastUpdate) {
        this.id = id;
        this.fasNroRadicacion = fasNroRadicacion;
        this.cccDemandante = cccDemandante;
        this.cccDemandado = cccDemandado;
        this.cccOrgano = cccOrgano;
        this.cccDistrito = cccDistrito;
        this.cccJuez = cccJuez;
        this.cccFechaInicio = cccFechaInicio;
        this.cccProceso = cccProceso;
        this.cccEspecialidad = cccEspecialidad;
        this.cccMateria = cccMateria;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="litIdLitigio", column=@Column(name="lit_id_litigio", nullable=false, length=10) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public M4sllCpeCejpjCId getId() {
        return this.id;
    }

    public void setId(M4sllCpeCejpjCId id) {
        this.id = id;
    }


    @Column(name="fas_nro_radicacion", length=30)
    public String getFasNroRadicacion() {
        return this.fasNroRadicacion;
    }

    public void setFasNroRadicacion(String fasNroRadicacion) {
        this.fasNroRadicacion = fasNroRadicacion;
    }


    @Column(name="ccc_demandante", length=4000)
    public String getCccDemandante() {
        return this.cccDemandante;
    }

    public void setCccDemandante(String cccDemandante) {
        this.cccDemandante = cccDemandante;
    }


    @Column(name="ccc_demandado", length=4000)
    public String getCccDemandado() {
        return this.cccDemandado;
    }

    public void setCccDemandado(String cccDemandado) {
        this.cccDemandado = cccDemandado;
    }


    @Column(name="ccc_organo", length=254)
    public String getCccOrgano() {
        return this.cccOrgano;
    }

    public void setCccOrgano(String cccOrgano) {
        this.cccOrgano = cccOrgano;
    }


    @Column(name="ccc_distrito", length=254)
    public String getCccDistrito() {
        return this.cccDistrito;
    }

    public void setCccDistrito(String cccDistrito) {
        this.cccDistrito = cccDistrito;
    }


    @Column(name="ccc_juez", length=254)
    public String getCccJuez() {
        return this.cccJuez;
    }

    public void setCccJuez(String cccJuez) {
        this.cccJuez = cccJuez;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ccc_fecha_inicio", length=22)
    public Date getCccFechaInicio() {
        return this.cccFechaInicio;
    }

    public void setCccFechaInicio(Date cccFechaInicio) {
        this.cccFechaInicio = cccFechaInicio;
    }


    @Column(name="ccc_proceso", length=254)
    public String getCccProceso() {
        return this.cccProceso;
    }

    public void setCccProceso(String cccProceso) {
        this.cccProceso = cccProceso;
    }


    @Column(name="ccc_especialidad", length=254)
    public String getCccEspecialidad() {
        return this.cccEspecialidad;
    }

    public void setCccEspecialidad(String cccEspecialidad) {
        this.cccEspecialidad = cccEspecialidad;
    }


    @Column(name="ccc_materia", length=254)
    public String getCccMateria() {
        return this.cccMateria;
    }

    public void setCccMateria(String cccMateria) {
        this.cccMateria = cccMateria;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }




}


