package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllMtoSegInteId generated by hbm2java
 */
@Embeddable
public class M4sllMtoSegInteId  implements java.io.Serializable {


    private String idAppRole;
    private long msiSecuencia;
    private String idOrganization;

    public M4sllMtoSegInteId() {
    }

    public M4sllMtoSegInteId(String idAppRole, long msiSecuencia, String idOrganization) {
        this.idAppRole = idAppRole;
        this.msiSecuencia = msiSecuencia;
        this.idOrganization = idOrganization;
    }



    @Column(name="id_app_role", nullable=false, length=30)
    public String getIdAppRole() {
        return this.idAppRole;
    }

    public void setIdAppRole(String idAppRole) {
        this.idAppRole = idAppRole;
    }


    @Column(name="msi_secuencia", nullable=false)
    public long getMsiSecuencia() {
        return this.msiSecuencia;
    }

    public void setMsiSecuencia(long msiSecuencia) {
        this.msiSecuencia = msiSecuencia;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllMtoSegInteId) ) return false;
        M4sllMtoSegInteId castOther = ( M4sllMtoSegInteId ) other;

        return ( (this.getIdAppRole()==castOther.getIdAppRole()) || ( this.getIdAppRole()!=null && castOther.getIdAppRole()!=null && this.getIdAppRole().equals(castOther.getIdAppRole()) ) )
               && (this.getMsiSecuencia()==castOther.getMsiSecuencia())
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getIdAppRole() == null ? 0 : this.getIdAppRole().hashCode() );
        result = 37 * result + (int) this.getMsiSecuencia();
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


