package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sllTpRecurrenId generated by hbm2java
 */
@Embeddable
public class M4sllTpRecurrenId  implements java.io.Serializable {


    private String treIdRecurrencia;
    private String idOrganization;

    public M4sllTpRecurrenId() {
    }

    public M4sllTpRecurrenId(String treIdRecurrencia, String idOrganization) {
        this.treIdRecurrencia = treIdRecurrencia;
        this.idOrganization = idOrganization;
    }



    @Column(name="tre_id_recurrencia", nullable=false, length=3)
    public String getTreIdRecurrencia() {
        return this.treIdRecurrencia;
    }

    public void setTreIdRecurrencia(String treIdRecurrencia) {
        this.treIdRecurrencia = treIdRecurrencia;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof M4sllTpRecurrenId) ) return false;
        M4sllTpRecurrenId castOther = ( M4sllTpRecurrenId ) other;

        return ( (this.getTreIdRecurrencia()==castOther.getTreIdRecurrencia()) || ( this.getTreIdRecurrencia()!=null && castOther.getTreIdRecurrencia()!=null && this.getTreIdRecurrencia().equals(castOther.getTreIdRecurrencia()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getTreIdRecurrencia() == null ? 0 : this.getTreIdRecurrencia().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


