package com.prosegur.sllpe.domain;

import java.io.Serializable;
import javax.persistence.*;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;


/**
 * SllVwAutorReu generated by hbm2java
 */
@Entity
@Table(name = "sll_vw_autor_reu", schema = "sll")
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
public class SllVwAutorReu implements Serializable {
    private static final long serialVersionUID = 1L;


    private String mteIdTpEmpleado;
    private String aurAutorReu;
    private String aurCkPrincipal;
    @Id
    private Long aurSecuencia;
    private String entNmEntidad;
    private String entNroIdentificacion;
    private String litIdLitigio;
    private String tarIdTpAutorReu;
    private String tpeIdTpEntidad;
    private String tpiIdTpIdentificacion;
    private String eciIdCiudadAutor;
    private String mabApellido;
    private String mabNombre;
    private Long mabSecuencia;
    private String pexApellido;
    private String pexNombre;
    private String pexNroDocumento;
    private String stdIdPerson;
    private String stdFamName;
    private String stdFirstName;
    private String stdSsn;
    private String stdIdLegEnt;
    private String stdLegEnt;
    private String nombre;
    private Long stdHrPeriod;

    @Column(name = "mte_id_tp_empleado", length = 3)
    public String getMteIdTpEmpleado() {
        return this.mteIdTpEmpleado;
    }

    public void setMteIdTpEmpleado(String mteIdTpEmpleado) {
        this.mteIdTpEmpleado = mteIdTpEmpleado;
    }

    @Column(name = "aur_autor_reu", length = 1)
    public String getAurAutorReu() {
        return this.aurAutorReu;
    }

    public void setAurAutorReu(String aurAutorReu) {
        this.aurAutorReu = aurAutorReu;
    }

    @Column(name = "aur_ck_principal", length = 1)
    public String getAurCkPrincipal() {
        return this.aurCkPrincipal;
    }

    public void setAurCkPrincipal(String aurCkPrincipal) {
        this.aurCkPrincipal = aurCkPrincipal;
    }

    @Column(name = "aur_secuencia")
    public Long getAurSecuencia() {
        return this.aurSecuencia;
    }

    public void setAurSecuencia(Long aurSecuencia) {
        this.aurSecuencia = aurSecuencia;
    }

    @Column(name = "ent_nm_entidad", length = 254)
    public String getEntNmEntidad() {
        return this.entNmEntidad;
    }

    public void setEntNmEntidad(String entNmEntidad) {
        this.entNmEntidad = entNmEntidad;
    }

    @Column(name = "ent_nro_identificacion", length = 254)
    public String getEntNroIdentificacion() {
        return this.entNroIdentificacion;
    }

    public void setEntNroIdentificacion(String entNroIdentificacion) {
        this.entNroIdentificacion = entNroIdentificacion;
    }

    @Column(name = "lit_id_litigio", length = 10)
    public String getLitIdLitigio() {
        return this.litIdLitigio;
    }

    public void setLitIdLitigio(String litIdLitigio) {
        this.litIdLitigio = litIdLitigio;
    }

    @Column(name = "tar_id_tp_autor_reu", length = 3)
    public String getTarIdTpAutorReu() {
        return this.tarIdTpAutorReu;
    }

    public void setTarIdTpAutorReu(String tarIdTpAutorReu) {
        this.tarIdTpAutorReu = tarIdTpAutorReu;
    }

    @Column(name = "tpe_id_tp_entidad", length = 3)
    public String getTpeIdTpEntidad() {
        return this.tpeIdTpEntidad;
    }

    public void setTpeIdTpEntidad(String tpeIdTpEntidad) {
        this.tpeIdTpEntidad = tpeIdTpEntidad;
    }

    @Column(name = "tpi_id_tp_identificacion", length = 3)
    public String getTpiIdTpIdentificacion() {
        return this.tpiIdTpIdentificacion;
    }

    public void setTpiIdTpIdentificacion(String tpiIdTpIdentificacion) {
        this.tpiIdTpIdentificacion = tpiIdTpIdentificacion;
    }

    @Column(name = "eci_id_ciudad_autor", length = 3)
    public String getEciIdCiudadAutor() {
        return this.eciIdCiudadAutor;
    }

    public void setEciIdCiudadAutor(String eciIdCiudadAutor) {
        this.eciIdCiudadAutor = eciIdCiudadAutor;
    }

    @Column(name = "mab_apellido")
    public String getMabApellido() {
        return this.mabApellido;
    }

    public void setMabApellido(String mabApellido) {
        this.mabApellido = mabApellido;
    }

    @Column(name = "mab_nombre")
    public String getMabNombre() {
        return this.mabNombre;
    }

    public void setMabNombre(String mabNombre) {
        this.mabNombre = mabNombre;
    }

    @Column(name = "mab_secuencia")
    public Long getMabSecuencia() {
        return this.mabSecuencia;
    }

    public void setMabSecuencia(Long mabSecuencia) {
        this.mabSecuencia = mabSecuencia;
    }

    @Column(name = "pex_apellido", length = 254)
    public String getPexApellido() {
        return this.pexApellido;
    }

    public void setPexApellido(String pexApellido) {
        this.pexApellido = pexApellido;
    }

    @Column(name = "pex_nombre", length = 254)
    public String getPexNombre() {
        return this.pexNombre;
    }

    public void setPexNombre(String pexNombre) {
        this.pexNombre = pexNombre;
    }

    @Column(name = "pex_nro_documento", length = 20)
    public String getPexNroDocumento() {
        return this.pexNroDocumento;
    }

    public void setPexNroDocumento(String pexNroDocumento) {
        this.pexNroDocumento = pexNroDocumento;
    }

    @Column(name = "std_id_person", length = 10)
    public String getStdIdPerson() {
        return this.stdIdPerson;
    }

    public void setStdIdPerson(String stdIdPerson) {
        this.stdIdPerson = stdIdPerson;
    }


    @Column(name = "std_fam_name", length = 50)
    public String getStdFamName() {
        return this.stdFamName;
    }

    public void setStdFamName(String stdFamName) {
        this.stdFamName = stdFamName;
    }

    @Column(name = "std_first_name", length = 50)
    public String getStdFirstName() {
        return this.stdFirstName;
    }

    public void setStdFirstName(String stdNFirstName) {
        this.stdFirstName = stdNFirstName;
    }

    @Column(name = "std_ssn", length = 20)
    public String getStdSsn() {
        return this.stdSsn;
    }

    public void setStdSsn(String stdSsn) {
        this.stdSsn = stdSsn;
    }

    @Column(name = "std_id_leg_ent", length = 9)
    public String getStdIdLegEnt() {
        return this.stdIdLegEnt;
    }

    public void setStdIdLegEnt(String stdIdLegEnt) {
        this.stdIdLegEnt = stdIdLegEnt;
    }

    @Column(name = "std_leg_ent", length = 62)
    public String getStdLegEnt() {
        return this.stdLegEnt;
    }

    public void setStdLegEnt(String stdLegEnt) {
        this.stdLegEnt = stdLegEnt;
    }

    @Column(name = "nombre", length = 254)
    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    @Column(name = "std_hr_period")
    public Long getStdHrPeriod() {
        return this.stdHrPeriod;
    }

    public void setStdHrPeriod(Long stdHrPeriod) {
        this.stdHrPeriod = stdHrPeriod;
    }

    ////////////////////////////////////////////////

    // jhipster-needle-entity-add-field - JHipster will add fields here
    public Long getId() {
        return this.aurSecuencia;
    }

    public void setId(Long aurSecuencia) {
        this.aurSecuencia = aurSecuencia;
    }

    ////////////////////////////////////////////////

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof SllVwAutorReu)) {
            return false;
        }
        return aurSecuencia != null && aurSecuencia.equals(((SllVwAutorReu) o).aurSecuencia);
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getMteIdTpEmpleado() == null ? 0 : this.getMteIdTpEmpleado().hashCode());
        result = 37 * result + (getAurAutorReu() == null ? 0 : this.getAurAutorReu().hashCode());
        result = 37 * result + (getAurCkPrincipal() == null ? 0 : this.getAurCkPrincipal().hashCode());
        result = 37 * result + (getAurSecuencia() == null ? 0 : this.getAurSecuencia().hashCode());
        result = 37 * result + (getEntNmEntidad() == null ? 0 : this.getEntNmEntidad().hashCode());
        result = 37 * result + (getEntNroIdentificacion() == null ? 0 : this.getEntNroIdentificacion().hashCode());
        result = 37 * result + (getLitIdLitigio() == null ? 0 : this.getLitIdLitigio().hashCode());
        result = 37 * result + (getTarIdTpAutorReu() == null ? 0 : this.getTarIdTpAutorReu().hashCode());
        result = 37 * result + (getTpeIdTpEntidad() == null ? 0 : this.getTpeIdTpEntidad().hashCode());
        result = 37 * result + (getTpiIdTpIdentificacion() == null ? 0 : this.getTpiIdTpIdentificacion().hashCode());
        result = 37 * result + (getEciIdCiudadAutor() == null ? 0 : this.getEciIdCiudadAutor().hashCode());
        result = 37 * result + (getMabApellido() == null ? 0 : this.getMabApellido().hashCode());
        result = 37 * result + (getMabNombre() == null ? 0 : this.getMabNombre().hashCode());
        result = 37 * result + (getMabSecuencia() == null ? 0 : this.getMabSecuencia().hashCode());
        result = 37 * result + (getPexApellido() == null ? 0 : this.getPexApellido().hashCode());
        result = 37 * result + (getPexNombre() == null ? 0 : this.getPexNombre().hashCode());
        result = 37 * result + (getPexNroDocumento() == null ? 0 : this.getPexNroDocumento().hashCode());
        result = 37 * result + (getStdIdPerson() == null ? 0 : this.getStdIdPerson().hashCode());
        result = 37 * result + (getStdFamName() == null ? 0 : this.getStdFamName().hashCode());
        result = 37 * result + (getStdFirstName() == null ? 0 : this.getStdFirstName().hashCode());
        result = 37 * result + (getStdSsn() == null ? 0 : this.getStdSsn().hashCode());
        result = 37 * result + (getStdIdLegEnt() == null ? 0 : this.getStdIdLegEnt().hashCode());
        result = 37 * result + (getStdLegEnt() == null ? 0 : this.getStdLegEnt().hashCode());
        result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
        result = 37 * result + (getStdHrPeriod() == null ? 0 : this.getStdHrPeriod().hashCode());
        return result;
    }

}
