package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:11:44 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdCountry generated by hbm2java
 */
@Entity
@Table(name="std_country"
            ,schema="public"
      )
public class StdCountry  implements java.io.Serializable {


    private StdCountryId id;
    private String stdNCountrybra;
    private String stdNCountryeng;
    private String stdNCountryesp;
    private String stdNCountryfra;
    private String stdNCountrygen;
    private String stdNCountryger;
    private String stdNCountryita;
    private String stdIdCountGroup;
    private String stdIdNacionality;
    private String stdNNacionalbra;
    private String stdNNacionaleng;
    private String stdNNacionalesp;
    private String stdNNacionalfra;
    private String stdNNacionalgen;
    private String stdNNacionalger;
    private String stdNNacionalita;
    private String stdIdCurrency;
    private String sfrIdNationality;
    private String sspIdNacionSs;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private Short stdIdCountDian;

    public StdCountry() {
    }


    public StdCountry(StdCountryId id) {
        this.id = id;
    }
    public StdCountry(StdCountryId id, String stdNCountrybra, String stdNCountryeng, String stdNCountryesp, String stdNCountryfra, String stdNCountrygen, String stdNCountryger, String stdNCountryita, String stdIdCountGroup, String stdIdNacionality, String stdNNacionalbra, String stdNNacionaleng, String stdNNacionalesp, String stdNNacionalfra, String stdNNacionalgen, String stdNNacionalger, String stdNNacionalita, String stdIdCurrency, String sfrIdNationality, String sspIdNacionSs, String idApprole, String idSecuser, Date dtLastUpdate, Short stdIdCountDian) {
        this.id = id;
        this.stdNCountrybra = stdNCountrybra;
        this.stdNCountryeng = stdNCountryeng;
        this.stdNCountryesp = stdNCountryesp;
        this.stdNCountryfra = stdNCountryfra;
        this.stdNCountrygen = stdNCountrygen;
        this.stdNCountryger = stdNCountryger;
        this.stdNCountryita = stdNCountryita;
        this.stdIdCountGroup = stdIdCountGroup;
        this.stdIdNacionality = stdIdNacionality;
        this.stdNNacionalbra = stdNNacionalbra;
        this.stdNNacionaleng = stdNNacionaleng;
        this.stdNNacionalesp = stdNNacionalesp;
        this.stdNNacionalfra = stdNNacionalfra;
        this.stdNNacionalgen = stdNNacionalgen;
        this.stdNNacionalger = stdNNacionalger;
        this.stdNNacionalita = stdNNacionalita;
        this.stdIdCurrency = stdIdCurrency;
        this.sfrIdNationality = sfrIdNationality;
        this.sspIdNacionSs = sspIdNacionSs;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.stdIdCountDian = stdIdCountDian;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="stdIdCountry", column=@Column(name="std_id_country", nullable=false, length=4) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public StdCountryId getId() {
        return this.id;
    }

    public void setId(StdCountryId id) {
        this.id = id;
    }


    @Column(name="std_n_countrybra", length=62)
    public String getStdNCountrybra() {
        return this.stdNCountrybra;
    }

    public void setStdNCountrybra(String stdNCountrybra) {
        this.stdNCountrybra = stdNCountrybra;
    }


    @Column(name="std_n_countryeng", length=62)
    public String getStdNCountryeng() {
        return this.stdNCountryeng;
    }

    public void setStdNCountryeng(String stdNCountryeng) {
        this.stdNCountryeng = stdNCountryeng;
    }


    @Column(name="std_n_countryesp", length=62)
    public String getStdNCountryesp() {
        return this.stdNCountryesp;
    }

    public void setStdNCountryesp(String stdNCountryesp) {
        this.stdNCountryesp = stdNCountryesp;
    }


    @Column(name="std_n_countryfra", length=62)
    public String getStdNCountryfra() {
        return this.stdNCountryfra;
    }

    public void setStdNCountryfra(String stdNCountryfra) {
        this.stdNCountryfra = stdNCountryfra;
    }


    @Column(name="std_n_countrygen", length=62)
    public String getStdNCountrygen() {
        return this.stdNCountrygen;
    }

    public void setStdNCountrygen(String stdNCountrygen) {
        this.stdNCountrygen = stdNCountrygen;
    }


    @Column(name="std_n_countryger", length=62)
    public String getStdNCountryger() {
        return this.stdNCountryger;
    }

    public void setStdNCountryger(String stdNCountryger) {
        this.stdNCountryger = stdNCountryger;
    }


    @Column(name="std_n_countryita", length=62)
    public String getStdNCountryita() {
        return this.stdNCountryita;
    }

    public void setStdNCountryita(String stdNCountryita) {
        this.stdNCountryita = stdNCountryita;
    }


    @Column(name="std_id_count_group", length=3)
    public String getStdIdCountGroup() {
        return this.stdIdCountGroup;
    }

    public void setStdIdCountGroup(String stdIdCountGroup) {
        this.stdIdCountGroup = stdIdCountGroup;
    }


    @Column(name="std_id_nacionality", length=3)
    public String getStdIdNacionality() {
        return this.stdIdNacionality;
    }

    public void setStdIdNacionality(String stdIdNacionality) {
        this.stdIdNacionality = stdIdNacionality;
    }


    @Column(name="std_n_nacionalbra", length=62)
    public String getStdNNacionalbra() {
        return this.stdNNacionalbra;
    }

    public void setStdNNacionalbra(String stdNNacionalbra) {
        this.stdNNacionalbra = stdNNacionalbra;
    }


    @Column(name="std_n_nacionaleng", length=62)
    public String getStdNNacionaleng() {
        return this.stdNNacionaleng;
    }

    public void setStdNNacionaleng(String stdNNacionaleng) {
        this.stdNNacionaleng = stdNNacionaleng;
    }


    @Column(name="std_n_nacionalesp", length=62)
    public String getStdNNacionalesp() {
        return this.stdNNacionalesp;
    }

    public void setStdNNacionalesp(String stdNNacionalesp) {
        this.stdNNacionalesp = stdNNacionalesp;
    }


    @Column(name="std_n_nacionalfra", length=62)
    public String getStdNNacionalfra() {
        return this.stdNNacionalfra;
    }

    public void setStdNNacionalfra(String stdNNacionalfra) {
        this.stdNNacionalfra = stdNNacionalfra;
    }


    @Column(name="std_n_nacionalgen", length=62)
    public String getStdNNacionalgen() {
        return this.stdNNacionalgen;
    }

    public void setStdNNacionalgen(String stdNNacionalgen) {
        this.stdNNacionalgen = stdNNacionalgen;
    }


    @Column(name="std_n_nacionalger", length=62)
    public String getStdNNacionalger() {
        return this.stdNNacionalger;
    }

    public void setStdNNacionalger(String stdNNacionalger) {
        this.stdNNacionalger = stdNNacionalger;
    }


    @Column(name="std_n_nacionalita", length=62)
    public String getStdNNacionalita() {
        return this.stdNNacionalita;
    }

    public void setStdNNacionalita(String stdNNacionalita) {
        this.stdNNacionalita = stdNNacionalita;
    }


    @Column(name="std_id_currency", length=3)
    public String getStdIdCurrency() {
        return this.stdIdCurrency;
    }

    public void setStdIdCurrency(String stdIdCurrency) {
        this.stdIdCurrency = stdIdCurrency;
    }


    @Column(name="sfr_id_nationality", length=2)
    public String getSfrIdNationality() {
        return this.sfrIdNationality;
    }

    public void setSfrIdNationality(String sfrIdNationality) {
        this.sfrIdNationality = sfrIdNationality;
    }


    @Column(name="ssp_id_nacion_ss", length=3)
    public String getSspIdNacionSs() {
        return this.sspIdNacionSs;
    }

    public void setSspIdNacionSs(String sspIdNacionSs) {
        this.sspIdNacionSs = sspIdNacionSs;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="std_id_count_dian")
    public Short getStdIdCountDian() {
        return this.stdIdCountDian;
    }

    public void setStdIdCountDian(Short stdIdCountDian) {
        this.stdIdCountDian = stdIdCountDian;
    }




}


