package com.prosegur.sllpe.domain;


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StdCountryId generated by hbm2java
 */
@Embeddable
public class StdCountryId  implements java.io.Serializable {


    private String stdIdCountry;
    private String idOrganization;

    public StdCountryId() {
    }

    public StdCountryId(String stdIdCountry, String idOrganization) {
        this.stdIdCountry = stdIdCountry;
        this.idOrganization = idOrganization;
    }



    @Column(name="std_id_country", nullable=false, length=4)
    public String getStdIdCountry() {
        return this.stdIdCountry;
    }

    public void setStdIdCountry(String stdIdCountry) {
        this.stdIdCountry = stdIdCountry;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof StdCountryId) ) return false;
        StdCountryId castOther = ( StdCountryId ) other;

        return ( (this.getStdIdCountry()==castOther.getStdIdCountry()) || ( this.getStdIdCountry()!=null && castOther.getStdIdCountry()!=null && this.getStdIdCountry().equals(castOther.getStdIdCountry()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getStdIdCountry() == null ? 0 : this.getStdIdCountry().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


