package com.prosegur.sllpe.domain;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdGeoDiv generated by hbm2java
 */
@Entity
@Table(name="std_geo_div"
            ,schema="public"
      )
public class StdGeoDiv  implements java.io.Serializable {


    private StdGeoDivId id;
    private String stdNGeoDiveng;
    private String stdNGeoDivesp;
    private String stdNGeoDivfra;
    private String stdNGeoDivger;
    private String stdNGeoDivbra;
    private String stdNGeoDivita;
    private String stdNGeoDivgen;
    private String smeIdCurp;
    private BigDecimal smePorcIlis;
    private String scbIdZonaUpc;
    private String sarIdProvAfip;
    private BigDecimal smePorcImpuesto;
    private String idApprole;
    private Short smeCalcImp;
    private String idSecuser;
    private String smeIdEstadoDim;
    private Date dtLastUpdate;

    public StdGeoDiv() {
    }


    public StdGeoDiv(StdGeoDivId id) {
        this.id = id;
    }
    public StdGeoDiv(StdGeoDivId id, String stdNGeoDiveng, String stdNGeoDivesp, String stdNGeoDivfra, String stdNGeoDivger, String stdNGeoDivbra, String stdNGeoDivita, String stdNGeoDivgen, String smeIdCurp, BigDecimal smePorcIlis, String scbIdZonaUpc, String sarIdProvAfip, BigDecimal smePorcImpuesto, String idApprole, Short smeCalcImp, String idSecuser, String smeIdEstadoDim, Date dtLastUpdate) {
        this.id = id;
        this.stdNGeoDiveng = stdNGeoDiveng;
        this.stdNGeoDivesp = stdNGeoDivesp;
        this.stdNGeoDivfra = stdNGeoDivfra;
        this.stdNGeoDivger = stdNGeoDivger;
        this.stdNGeoDivbra = stdNGeoDivbra;
        this.stdNGeoDivita = stdNGeoDivita;
        this.stdNGeoDivgen = stdNGeoDivgen;
        this.smeIdCurp = smeIdCurp;
        this.smePorcIlis = smePorcIlis;
        this.scbIdZonaUpc = scbIdZonaUpc;
        this.sarIdProvAfip = sarIdProvAfip;
        this.smePorcImpuesto = smePorcImpuesto;
        this.idApprole = idApprole;
        this.smeCalcImp = smeCalcImp;
        this.idSecuser = idSecuser;
        this.smeIdEstadoDim = smeIdEstadoDim;
        this.dtLastUpdate = dtLastUpdate;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="stdIdCountry", column=@Column(name="std_id_country", nullable=false, length=4) ),
        @AttributeOverride(name="stdIdGeoDiv", column=@Column(name="std_id_geo_div", nullable=false, length=4) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public StdGeoDivId getId() {
        return this.id;
    }

    public void setId(StdGeoDivId id) {
        this.id = id;
    }


    @Column(name="std_n_geo_diveng", length=62)
    public String getStdNGeoDiveng() {
        return this.stdNGeoDiveng;
    }

    public void setStdNGeoDiveng(String stdNGeoDiveng) {
        this.stdNGeoDiveng = stdNGeoDiveng;
    }


    @Column(name="std_n_geo_divesp", length=62)
    public String getStdNGeoDivesp() {
        return this.stdNGeoDivesp;
    }

    public void setStdNGeoDivesp(String stdNGeoDivesp) {
        this.stdNGeoDivesp = stdNGeoDivesp;
    }


    @Column(name="std_n_geo_divfra", length=62)
    public String getStdNGeoDivfra() {
        return this.stdNGeoDivfra;
    }

    public void setStdNGeoDivfra(String stdNGeoDivfra) {
        this.stdNGeoDivfra = stdNGeoDivfra;
    }


    @Column(name="std_n_geo_divger", length=62)
    public String getStdNGeoDivger() {
        return this.stdNGeoDivger;
    }

    public void setStdNGeoDivger(String stdNGeoDivger) {
        this.stdNGeoDivger = stdNGeoDivger;
    }


    @Column(name="std_n_geo_divbra", length=62)
    public String getStdNGeoDivbra() {
        return this.stdNGeoDivbra;
    }

    public void setStdNGeoDivbra(String stdNGeoDivbra) {
        this.stdNGeoDivbra = stdNGeoDivbra;
    }


    @Column(name="std_n_geo_divita", length=62)
    public String getStdNGeoDivita() {
        return this.stdNGeoDivita;
    }

    public void setStdNGeoDivita(String stdNGeoDivita) {
        this.stdNGeoDivita = stdNGeoDivita;
    }


    @Column(name="std_n_geo_divgen", length=62)
    public String getStdNGeoDivgen() {
        return this.stdNGeoDivgen;
    }

    public void setStdNGeoDivgen(String stdNGeoDivgen) {
        this.stdNGeoDivgen = stdNGeoDivgen;
    }


    @Column(name="sme_id_curp", length=2)
    public String getSmeIdCurp() {
        return this.smeIdCurp;
    }

    public void setSmeIdCurp(String smeIdCurp) {
        this.smeIdCurp = smeIdCurp;
    }


    @Column(name="sme_porc_ilis", precision=7, scale=4)
    public BigDecimal getSmePorcIlis() {
        return this.smePorcIlis;
    }

    public void setSmePorcIlis(BigDecimal smePorcIlis) {
        this.smePorcIlis = smePorcIlis;
    }


    @Column(name="scb_id_zona_upc", length=3)
    public String getScbIdZonaUpc() {
        return this.scbIdZonaUpc;
    }

    public void setScbIdZonaUpc(String scbIdZonaUpc) {
        this.scbIdZonaUpc = scbIdZonaUpc;
    }


    @Column(name="sar_id_prov_afip", length=4)
    public String getSarIdProvAfip() {
        return this.sarIdProvAfip;
    }

    public void setSarIdProvAfip(String sarIdProvAfip) {
        this.sarIdProvAfip = sarIdProvAfip;
    }


    @Column(name="sme_porc_impuesto", precision=5)
    public BigDecimal getSmePorcImpuesto() {
        return this.smePorcImpuesto;
    }

    public void setSmePorcImpuesto(BigDecimal smePorcImpuesto) {
        this.smePorcImpuesto = smePorcImpuesto;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="sme_calc_imp")
    public Short getSmeCalcImp() {
        return this.smeCalcImp;
    }

    public void setSmeCalcImp(Short smeCalcImp) {
        this.smeCalcImp = smeCalcImp;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }


    @Column(name="sme_id_estado_dim", length=4)
    public String getSmeIdEstadoDim() {
        return this.smeIdEstadoDim;
    }

    public void setSmeIdEstadoDim(String smeIdEstadoDim) {
        this.smeIdEstadoDim = smeIdEstadoDim;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }




}


