package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:12:18 AM by Hibernate Tools 5.2.0.Final


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdLegEnt generated by hbm2java
 */
@Entity
@Table(name="std_leg_ent"
            ,schema="public"
      )
public class StdLegEnt  implements java.io.Serializable {


    private StdLegEntId id;
    private String stdNLegEnt;
    private Date stdDtStart;
    private Date stdDtEnd;
    private String stdDescription;
    private String sspIdResponsable;
    private String sspIdTpIdLgal;
    private String sspIdPaisEmisor;
    private String sfrIdLegalHoldi;
    private String sfrIdActivSecto;
    private String sspIdLegal;
    private String sspCargoCerteng;
    private String sspCargoCertesp;
    private String sspCargoCertfra;
    private String sspCargoCertger;
    private String sspCargoCertbra;
    private String sspCargoCertita;
    private String sspCargoCertgen;
    private String sspCodLocEmpr;
    private String sspFirmtCertHab;
    private String sspIdLegCerHab;
    private Short sspIdTpAlfEmp;
    private String sspLitPluriemple;
    private String sspNumTrabEmpr;
    private String sspSubcif;
    private String stdNidEnt;
    private String stdNidAct;
    private String sfrLegalEntityL;
    private Short sfrRegLegent;
    private Short sfrRegSubLegent;
    private String spoIdNatureza;
    private String spoIdActividade;
    private Date spoDtPublicBt;
    private Date spoDtUltTabSal;
    private String spoInstRegTrab;
    private BigDecimal spoCapitalSocial;
    private BigDecimal spoVolumeVendas;
    private BigDecimal spoReparticaoPer;
    private BigDecimal spoRepPercEstra;
    private BigDecimal spoRepPercPub;
    private String spoAnoLegEnt;
    private String spoCodConcelho;
    private String sarIdArt;
    private String ccoCodigoInterno;
    private Integer smeSiem;
    private String ccoIdModeloNoti;
    private Date ccoDtInicioCort;
    private String smeIdRegFiscal;
    private Short carIdBaseLiquidacion;
    private Date ccoDtFinCorte;
    private String ccoUltIdHr;
    private Long ccoUltPedidoDin;
    private String ccoLogo;
    private byte[] ccoPlantilla;
    private Short ccoCkBloquear;
    private String cfrIdEmpAnalitica;
    private String ccoCodigoErp;
    private String ccoCodigoAurus;
    private String ccoIdNegocio;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String smeIdComisionMixta;
    private Date smeFecPresDim;
    private String smeFolioOperac;
    private String sspCargoCertHab;
    private Short carIdBaseLiquid;
    private String codFilialBrasil;
    private String cclInterfase;
    private BigDecimal cmxFactorSueldoNominal;
    private String cpeCodigoCorp;
    private String cpeNumRucCia;
    private String cpeRegPatronal;
    private String cpeGiroCia;
    private String cpeSituacionReg;
    private String cpeCiudadCia;
    private String smxRfc;
    private String carNumPrestadora;
    private String cuyCkCajaComp;

    public StdLegEnt() {
    }


    public StdLegEnt(StdLegEntId id) {
        this.id = id;
    }
    public StdLegEnt(StdLegEntId id, String stdNLegEnt, Date stdDtStart, Date stdDtEnd, String stdDescription, String sspIdResponsable, String sspIdTpIdLgal, String sspIdPaisEmisor, String sfrIdLegalHoldi, String sfrIdActivSecto, String sspIdLegal, String sspCargoCerteng, String sspCargoCertesp, String sspCargoCertfra, String sspCargoCertger, String sspCargoCertbra, String sspCargoCertita, String sspCargoCertgen, String sspCodLocEmpr, String sspFirmtCertHab, String sspIdLegCerHab, Short sspIdTpAlfEmp, String sspLitPluriemple, String sspNumTrabEmpr, String sspSubcif, String stdNidEnt, String stdNidAct, String sfrLegalEntityL, Short sfrRegLegent, Short sfrRegSubLegent, String spoIdNatureza, String spoIdActividade, Date spoDtPublicBt, Date spoDtUltTabSal, String spoInstRegTrab, BigDecimal spoCapitalSocial, BigDecimal spoVolumeVendas, BigDecimal spoReparticaoPer, BigDecimal spoRepPercEstra, BigDecimal spoRepPercPub, String spoAnoLegEnt, String spoCodConcelho, String sarIdArt, String ccoCodigoInterno, Integer smeSiem, String ccoIdModeloNoti, Date ccoDtInicioCort, String smeIdRegFiscal, Short carIdBaseLiquidacion, Date ccoDtFinCorte, String ccoUltIdHr, Long ccoUltPedidoDin, String ccoLogo, byte[] ccoPlantilla, Short ccoCkBloquear, String cfrIdEmpAnalitica, String ccoCodigoErp, String ccoCodigoAurus, String ccoIdNegocio, String idApprole, String idSecuser, Date dtLastUpdate, String smeIdComisionMixta, Date smeFecPresDim, String smeFolioOperac, String sspCargoCertHab, Short carIdBaseLiquid, String codFilialBrasil, String cclInterfase, BigDecimal cmxFactorSueldoNominal, String cpeCodigoCorp, String cpeNumRucCia, String cpeRegPatronal, String cpeGiroCia, String cpeSituacionReg, String cpeCiudadCia, String smxRfc, String carNumPrestadora, String cuyCkCajaComp) {
        this.id = id;
        this.stdNLegEnt = stdNLegEnt;
        this.stdDtStart = stdDtStart;
        this.stdDtEnd = stdDtEnd;
        this.stdDescription = stdDescription;
        this.sspIdResponsable = sspIdResponsable;
        this.sspIdTpIdLgal = sspIdTpIdLgal;
        this.sspIdPaisEmisor = sspIdPaisEmisor;
        this.sfrIdLegalHoldi = sfrIdLegalHoldi;
        this.sfrIdActivSecto = sfrIdActivSecto;
        this.sspIdLegal = sspIdLegal;
        this.sspCargoCerteng = sspCargoCerteng;
        this.sspCargoCertesp = sspCargoCertesp;
        this.sspCargoCertfra = sspCargoCertfra;
        this.sspCargoCertger = sspCargoCertger;
        this.sspCargoCertbra = sspCargoCertbra;
        this.sspCargoCertita = sspCargoCertita;
        this.sspCargoCertgen = sspCargoCertgen;
        this.sspCodLocEmpr = sspCodLocEmpr;
        this.sspFirmtCertHab = sspFirmtCertHab;
        this.sspIdLegCerHab = sspIdLegCerHab;
        this.sspIdTpAlfEmp = sspIdTpAlfEmp;
        this.sspLitPluriemple = sspLitPluriemple;
        this.sspNumTrabEmpr = sspNumTrabEmpr;
        this.sspSubcif = sspSubcif;
        this.stdNidEnt = stdNidEnt;
        this.stdNidAct = stdNidAct;
        this.sfrLegalEntityL = sfrLegalEntityL;
        this.sfrRegLegent = sfrRegLegent;
        this.sfrRegSubLegent = sfrRegSubLegent;
        this.spoIdNatureza = spoIdNatureza;
        this.spoIdActividade = spoIdActividade;
        this.spoDtPublicBt = spoDtPublicBt;
        this.spoDtUltTabSal = spoDtUltTabSal;
        this.spoInstRegTrab = spoInstRegTrab;
        this.spoCapitalSocial = spoCapitalSocial;
        this.spoVolumeVendas = spoVolumeVendas;
        this.spoReparticaoPer = spoReparticaoPer;
        this.spoRepPercEstra = spoRepPercEstra;
        this.spoRepPercPub = spoRepPercPub;
        this.spoAnoLegEnt = spoAnoLegEnt;
        this.spoCodConcelho = spoCodConcelho;
        this.sarIdArt = sarIdArt;
        this.ccoCodigoInterno = ccoCodigoInterno;
        this.smeSiem = smeSiem;
        this.ccoIdModeloNoti = ccoIdModeloNoti;
        this.ccoDtInicioCort = ccoDtInicioCort;
        this.smeIdRegFiscal = smeIdRegFiscal;
        this.carIdBaseLiquidacion = carIdBaseLiquidacion;
        this.ccoDtFinCorte = ccoDtFinCorte;
        this.ccoUltIdHr = ccoUltIdHr;
        this.ccoUltPedidoDin = ccoUltPedidoDin;
        this.ccoLogo = ccoLogo;
        this.ccoPlantilla = ccoPlantilla;
        this.ccoCkBloquear = ccoCkBloquear;
        this.cfrIdEmpAnalitica = cfrIdEmpAnalitica;
        this.ccoCodigoErp = ccoCodigoErp;
        this.ccoCodigoAurus = ccoCodigoAurus;
        this.ccoIdNegocio = ccoIdNegocio;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.smeIdComisionMixta = smeIdComisionMixta;
        this.smeFecPresDim = smeFecPresDim;
        this.smeFolioOperac = smeFolioOperac;
        this.sspCargoCertHab = sspCargoCertHab;
        this.carIdBaseLiquid = carIdBaseLiquid;
        this.codFilialBrasil = codFilialBrasil;
        this.cclInterfase = cclInterfase;
        this.cmxFactorSueldoNominal = cmxFactorSueldoNominal;
        this.cpeCodigoCorp = cpeCodigoCorp;
        this.cpeNumRucCia = cpeNumRucCia;
        this.cpeRegPatronal = cpeRegPatronal;
        this.cpeGiroCia = cpeGiroCia;
        this.cpeSituacionReg = cpeSituacionReg;
        this.cpeCiudadCia = cpeCiudadCia;
        this.smxRfc = smxRfc;
        this.carNumPrestadora = carNumPrestadora;
        this.cuyCkCajaComp = cuyCkCajaComp;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="stdIdLegEnt", column=@Column(name="std_id_leg_ent", nullable=false, length=9) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public StdLegEntId getId() {
        return this.id;
    }

    public void setId(StdLegEntId id) {
        this.id = id;
    }


    @Column(name="std_n_leg_ent", length=62)
    public String getStdNLegEnt() {
        return this.stdNLegEnt;
    }

    public void setStdNLegEnt(String stdNLegEnt) {
        this.stdNLegEnt = stdNLegEnt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_dt_start", length=22)
    public Date getStdDtStart() {
        return this.stdDtStart;
    }

    public void setStdDtStart(Date stdDtStart) {
        this.stdDtStart = stdDtStart;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_dt_end", length=22)
    public Date getStdDtEnd() {
        return this.stdDtEnd;
    }

    public void setStdDtEnd(Date stdDtEnd) {
        this.stdDtEnd = stdDtEnd;
    }


    @Column(name="std_description", length=254)
    public String getStdDescription() {
        return this.stdDescription;
    }

    public void setStdDescription(String stdDescription) {
        this.stdDescription = stdDescription;
    }


    @Column(name="ssp_id_responsable", length=10)
    public String getSspIdResponsable() {
        return this.sspIdResponsable;
    }

    public void setSspIdResponsable(String sspIdResponsable) {
        this.sspIdResponsable = sspIdResponsable;
    }


    @Column(name="ssp_id_tp_id_lgal", length=1)
    public String getSspIdTpIdLgal() {
        return this.sspIdTpIdLgal;
    }

    public void setSspIdTpIdLgal(String sspIdTpIdLgal) {
        this.sspIdTpIdLgal = sspIdTpIdLgal;
    }


    @Column(name="ssp_id_pais_emisor", length=4)
    public String getSspIdPaisEmisor() {
        return this.sspIdPaisEmisor;
    }

    public void setSspIdPaisEmisor(String sspIdPaisEmisor) {
        this.sspIdPaisEmisor = sspIdPaisEmisor;
    }


    @Column(name="sfr_id_legal_holdi", length=9)
    public String getSfrIdLegalHoldi() {
        return this.sfrIdLegalHoldi;
    }

    public void setSfrIdLegalHoldi(String sfrIdLegalHoldi) {
        this.sfrIdLegalHoldi = sfrIdLegalHoldi;
    }


    @Column(name="sfr_id_activ_secto", length=5)
    public String getSfrIdActivSecto() {
        return this.sfrIdActivSecto;
    }

    public void setSfrIdActivSecto(String sfrIdActivSecto) {
        this.sfrIdActivSecto = sfrIdActivSecto;
    }


    @Column(name="ssp_id_legal", length=10)
    public String getSspIdLegal() {
        return this.sspIdLegal;
    }

    public void setSspIdLegal(String sspIdLegal) {
        this.sspIdLegal = sspIdLegal;
    }


    @Column(name="ssp_cargo_certeng", length=40)
    public String getSspCargoCerteng() {
        return this.sspCargoCerteng;
    }

    public void setSspCargoCerteng(String sspCargoCerteng) {
        this.sspCargoCerteng = sspCargoCerteng;
    }


    @Column(name="ssp_cargo_certesp", length=40)
    public String getSspCargoCertesp() {
        return this.sspCargoCertesp;
    }

    public void setSspCargoCertesp(String sspCargoCertesp) {
        this.sspCargoCertesp = sspCargoCertesp;
    }


    @Column(name="ssp_cargo_certfra", length=40)
    public String getSspCargoCertfra() {
        return this.sspCargoCertfra;
    }

    public void setSspCargoCertfra(String sspCargoCertfra) {
        this.sspCargoCertfra = sspCargoCertfra;
    }


    @Column(name="ssp_cargo_certger", length=40)
    public String getSspCargoCertger() {
        return this.sspCargoCertger;
    }

    public void setSspCargoCertger(String sspCargoCertger) {
        this.sspCargoCertger = sspCargoCertger;
    }


    @Column(name="ssp_cargo_certbra", length=40)
    public String getSspCargoCertbra() {
        return this.sspCargoCertbra;
    }

    public void setSspCargoCertbra(String sspCargoCertbra) {
        this.sspCargoCertbra = sspCargoCertbra;
    }


    @Column(name="ssp_cargo_certita", length=40)
    public String getSspCargoCertita() {
        return this.sspCargoCertita;
    }

    public void setSspCargoCertita(String sspCargoCertita) {
        this.sspCargoCertita = sspCargoCertita;
    }


    @Column(name="ssp_cargo_certgen", length=40)
    public String getSspCargoCertgen() {
        return this.sspCargoCertgen;
    }

    public void setSspCargoCertgen(String sspCargoCertgen) {
        this.sspCargoCertgen = sspCargoCertgen;
    }


    @Column(name="ssp_cod_loc_empr", length=5)
    public String getSspCodLocEmpr() {
        return this.sspCodLocEmpr;
    }

    public void setSspCodLocEmpr(String sspCodLocEmpr) {
        this.sspCodLocEmpr = sspCodLocEmpr;
    }


    @Column(name="ssp_firmt_cert_hab", length=40)
    public String getSspFirmtCertHab() {
        return this.sspFirmtCertHab;
    }

    public void setSspFirmtCertHab(String sspFirmtCertHab) {
        this.sspFirmtCertHab = sspFirmtCertHab;
    }


    @Column(name="ssp_id_leg_cer_hab", length=9)
    public String getSspIdLegCerHab() {
        return this.sspIdLegCerHab;
    }

    public void setSspIdLegCerHab(String sspIdLegCerHab) {
        this.sspIdLegCerHab = sspIdLegCerHab;
    }


    @Column(name="ssp_id_tp_alf_emp")
    public Short getSspIdTpAlfEmp() {
        return this.sspIdTpAlfEmp;
    }

    public void setSspIdTpAlfEmp(Short sspIdTpAlfEmp) {
        this.sspIdTpAlfEmp = sspIdTpAlfEmp;
    }


    @Column(name="ssp_lit_pluriemple", length=50)
    public String getSspLitPluriemple() {
        return this.sspLitPluriemple;
    }

    public void setSspLitPluriemple(String sspLitPluriemple) {
        this.sspLitPluriemple = sspLitPluriemple;
    }


    @Column(name="ssp_num_trab_empr", length=10)
    public String getSspNumTrabEmpr() {
        return this.sspNumTrabEmpr;
    }

    public void setSspNumTrabEmpr(String sspNumTrabEmpr) {
        this.sspNumTrabEmpr = sspNumTrabEmpr;
    }


    @Column(name="ssp_subcif", length=2)
    public String getSspSubcif() {
        return this.sspSubcif;
    }

    public void setSspSubcif(String sspSubcif) {
        this.sspSubcif = sspSubcif;
    }


    @Column(name="std_nid_ent", length=14)
    public String getStdNidEnt() {
        return this.stdNidEnt;
    }

    public void setStdNidEnt(String stdNidEnt) {
        this.stdNidEnt = stdNidEnt;
    }


    @Column(name="std_nid_act", length=5)
    public String getStdNidAct() {
        return this.stdNidAct;
    }

    public void setStdNidAct(String stdNidAct) {
        this.stdNidAct = stdNidAct;
    }


    @Column(name="sfr_legal_entity_l", length=62)
    public String getSfrLegalEntityL() {
        return this.sfrLegalEntityL;
    }

    public void setSfrLegalEntityL(String sfrLegalEntityL) {
        this.sfrLegalEntityL = sfrLegalEntityL;
    }


    @Column(name="sfr_reg_legent")
    public Short getSfrRegLegent() {
        return this.sfrRegLegent;
    }

    public void setSfrRegLegent(Short sfrRegLegent) {
        this.sfrRegLegent = sfrRegLegent;
    }


    @Column(name="sfr_reg_sub_legent")
    public Short getSfrRegSubLegent() {
        return this.sfrRegSubLegent;
    }

    public void setSfrRegSubLegent(Short sfrRegSubLegent) {
        this.sfrRegSubLegent = sfrRegSubLegent;
    }


    @Column(name="spo_id_natureza", length=6)
    public String getSpoIdNatureza() {
        return this.spoIdNatureza;
    }

    public void setSpoIdNatureza(String spoIdNatureza) {
        this.spoIdNatureza = spoIdNatureza;
    }


    @Column(name="spo_id_actividade", length=6)
    public String getSpoIdActividade() {
        return this.spoIdActividade;
    }

    public void setSpoIdActividade(String spoIdActividade) {
        this.spoIdActividade = spoIdActividade;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="spo_dt_public_bt", length=22)
    public Date getSpoDtPublicBt() {
        return this.spoDtPublicBt;
    }

    public void setSpoDtPublicBt(Date spoDtPublicBt) {
        this.spoDtPublicBt = spoDtPublicBt;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="spo_dt_ult_tab_sal", length=22)
    public Date getSpoDtUltTabSal() {
        return this.spoDtUltTabSal;
    }

    public void setSpoDtUltTabSal(Date spoDtUltTabSal) {
        this.spoDtUltTabSal = spoDtUltTabSal;
    }


    @Column(name="spo_inst_reg_trab", length=60)
    public String getSpoInstRegTrab() {
        return this.spoInstRegTrab;
    }

    public void setSpoInstRegTrab(String spoInstRegTrab) {
        this.spoInstRegTrab = spoInstRegTrab;
    }


    @Column(name="spo_capital_social", precision=14, scale=4)
    public BigDecimal getSpoCapitalSocial() {
        return this.spoCapitalSocial;
    }

    public void setSpoCapitalSocial(BigDecimal spoCapitalSocial) {
        this.spoCapitalSocial = spoCapitalSocial;
    }


    @Column(name="spo_volume_vendas", precision=14, scale=4)
    public BigDecimal getSpoVolumeVendas() {
        return this.spoVolumeVendas;
    }

    public void setSpoVolumeVendas(BigDecimal spoVolumeVendas) {
        this.spoVolumeVendas = spoVolumeVendas;
    }


    @Column(name="spo_reparticao_per", precision=5, scale=1)
    public BigDecimal getSpoReparticaoPer() {
        return this.spoReparticaoPer;
    }

    public void setSpoReparticaoPer(BigDecimal spoReparticaoPer) {
        this.spoReparticaoPer = spoReparticaoPer;
    }


    @Column(name="spo_rep_perc_estra", precision=5, scale=1)
    public BigDecimal getSpoRepPercEstra() {
        return this.spoRepPercEstra;
    }

    public void setSpoRepPercEstra(BigDecimal spoRepPercEstra) {
        this.spoRepPercEstra = spoRepPercEstra;
    }


    @Column(name="spo_rep_perc_pub", precision=5, scale=1)
    public BigDecimal getSpoRepPercPub() {
        return this.spoRepPercPub;
    }

    public void setSpoRepPercPub(BigDecimal spoRepPercPub) {
        this.spoRepPercPub = spoRepPercPub;
    }


    @Column(name="spo_ano_leg_ent", length=4)
    public String getSpoAnoLegEnt() {
        return this.spoAnoLegEnt;
    }

    public void setSpoAnoLegEnt(String spoAnoLegEnt) {
        this.spoAnoLegEnt = spoAnoLegEnt;
    }


    @Column(name="spo_cod_concelho", length=4)
    public String getSpoCodConcelho() {
        return this.spoCodConcelho;
    }

    public void setSpoCodConcelho(String spoCodConcelho) {
        this.spoCodConcelho = spoCodConcelho;
    }


    @Column(name="sar_id_art", length=11)
    public String getSarIdArt() {
        return this.sarIdArt;
    }

    public void setSarIdArt(String sarIdArt) {
        this.sarIdArt = sarIdArt;
    }


    @Column(name="cco_codigo_interno", length=2)
    public String getCcoCodigoInterno() {
        return this.ccoCodigoInterno;
    }

    public void setCcoCodigoInterno(String ccoCodigoInterno) {
        this.ccoCodigoInterno = ccoCodigoInterno;
    }


    @Column(name="sme_siem")
    public Integer getSmeSiem() {
        return this.smeSiem;
    }

    public void setSmeSiem(Integer smeSiem) {
        this.smeSiem = smeSiem;
    }


    @Column(name="cco_id_modelo_noti", length=3)
    public String getCcoIdModeloNoti() {
        return this.ccoIdModeloNoti;
    }

    public void setCcoIdModeloNoti(String ccoIdModeloNoti) {
        this.ccoIdModeloNoti = ccoIdModeloNoti;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cco_dt_inicio_cort", length=22)
    public Date getCcoDtInicioCort() {
        return this.ccoDtInicioCort;
    }

    public void setCcoDtInicioCort(Date ccoDtInicioCort) {
        this.ccoDtInicioCort = ccoDtInicioCort;
    }


    @Column(name="sme_id_reg_fiscal", length=4)
    public String getSmeIdRegFiscal() {
        return this.smeIdRegFiscal;
    }

    public void setSmeIdRegFiscal(String smeIdRegFiscal) {
        this.smeIdRegFiscal = smeIdRegFiscal;
    }


    @Column(name="car_id_base_liquidacion")
    public Short getCarIdBaseLiquidacion() {
        return this.carIdBaseLiquidacion;
    }

    public void setCarIdBaseLiquidacion(Short carIdBaseLiquidacion) {
        this.carIdBaseLiquidacion = carIdBaseLiquidacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cco_dt_fin_corte", length=22)
    public Date getCcoDtFinCorte() {
        return this.ccoDtFinCorte;
    }

    public void setCcoDtFinCorte(Date ccoDtFinCorte) {
        this.ccoDtFinCorte = ccoDtFinCorte;
    }


    @Column(name="cco_ult_id_hr", length=10)
    public String getCcoUltIdHr() {
        return this.ccoUltIdHr;
    }

    public void setCcoUltIdHr(String ccoUltIdHr) {
        this.ccoUltIdHr = ccoUltIdHr;
    }


    @Column(name="cco_ult_pedido_din")
    public Long getCcoUltPedidoDin() {
        return this.ccoUltPedidoDin;
    }

    public void setCcoUltPedidoDin(Long ccoUltPedidoDin) {
        this.ccoUltPedidoDin = ccoUltPedidoDin;
    }


    @Column(name="cco_logo", length=254)
    public String getCcoLogo() {
        return this.ccoLogo;
    }

    public void setCcoLogo(String ccoLogo) {
        this.ccoLogo = ccoLogo;
    }


    @Column(name="cco_plantilla")
    public byte[] getCcoPlantilla() {
        return this.ccoPlantilla;
    }

    public void setCcoPlantilla(byte[] ccoPlantilla) {
        this.ccoPlantilla = ccoPlantilla;
    }


    @Column(name="cco_ck_bloquear")
    public Short getCcoCkBloquear() {
        return this.ccoCkBloquear;
    }

    public void setCcoCkBloquear(Short ccoCkBloquear) {
        this.ccoCkBloquear = ccoCkBloquear;
    }


    @Column(name="cfr_id_emp_analitica", length=8)
    public String getCfrIdEmpAnalitica() {
        return this.cfrIdEmpAnalitica;
    }

    public void setCfrIdEmpAnalitica(String cfrIdEmpAnalitica) {
        this.cfrIdEmpAnalitica = cfrIdEmpAnalitica;
    }


    @Column(name="cco_codigo_erp", length=10)
    public String getCcoCodigoErp() {
        return this.ccoCodigoErp;
    }

    public void setCcoCodigoErp(String ccoCodigoErp) {
        this.ccoCodigoErp = ccoCodigoErp;
    }


    @Column(name="cco_codigo_aurus", length=10)
    public String getCcoCodigoAurus() {
        return this.ccoCodigoAurus;
    }

    public void setCcoCodigoAurus(String ccoCodigoAurus) {
        this.ccoCodigoAurus = ccoCodigoAurus;
    }


    @Column(name="cco_id_negocio", length=3)
    public String getCcoIdNegocio() {
        return this.ccoIdNegocio;
    }

    public void setCcoIdNegocio(String ccoIdNegocio) {
        this.ccoIdNegocio = ccoIdNegocio;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="sme_id_comision_mixta", length=20)
    public String getSmeIdComisionMixta() {
        return this.smeIdComisionMixta;
    }

    public void setSmeIdComisionMixta(String smeIdComisionMixta) {
        this.smeIdComisionMixta = smeIdComisionMixta;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sme_fec_pres_dim", length=22)
    public Date getSmeFecPresDim() {
        return this.smeFecPresDim;
    }

    public void setSmeFecPresDim(Date smeFecPresDim) {
        this.smeFecPresDim = smeFecPresDim;
    }


    @Column(name="sme_folio_operac", length=14)
    public String getSmeFolioOperac() {
        return this.smeFolioOperac;
    }

    public void setSmeFolioOperac(String smeFolioOperac) {
        this.smeFolioOperac = smeFolioOperac;
    }


    @Column(name="ssp_cargo_cert_hab", length=40)
    public String getSspCargoCertHab() {
        return this.sspCargoCertHab;
    }

    public void setSspCargoCertHab(String sspCargoCertHab) {
        this.sspCargoCertHab = sspCargoCertHab;
    }


    @Column(name="car_id_base_liquid")
    public Short getCarIdBaseLiquid() {
        return this.carIdBaseLiquid;
    }

    public void setCarIdBaseLiquid(Short carIdBaseLiquid) {
        this.carIdBaseLiquid = carIdBaseLiquid;
    }


    @Column(name="cod_filial_brasil", length=10)
    public String getCodFilialBrasil() {
        return this.codFilialBrasil;
    }

    public void setCodFilialBrasil(String codFilialBrasil) {
        this.codFilialBrasil = codFilialBrasil;
    }


    @Column(name="ccl_interfase", length=1)
    public String getCclInterfase() {
        return this.cclInterfase;
    }

    public void setCclInterfase(String cclInterfase) {
        this.cclInterfase = cclInterfase;
    }


    @Column(name="cmx_factor_sueldo_nominal", precision=18, scale=5)
    public BigDecimal getCmxFactorSueldoNominal() {
        return this.cmxFactorSueldoNominal;
    }

    public void setCmxFactorSueldoNominal(BigDecimal cmxFactorSueldoNominal) {
        this.cmxFactorSueldoNominal = cmxFactorSueldoNominal;
    }


    @Column(name="cpe_codigo_corp", length=2)
    public String getCpeCodigoCorp() {
        return this.cpeCodigoCorp;
    }

    public void setCpeCodigoCorp(String cpeCodigoCorp) {
        this.cpeCodigoCorp = cpeCodigoCorp;
    }


    @Column(name="cpe_num_ruc_cia", length=15)
    public String getCpeNumRucCia() {
        return this.cpeNumRucCia;
    }

    public void setCpeNumRucCia(String cpeNumRucCia) {
        this.cpeNumRucCia = cpeNumRucCia;
    }


    @Column(name="cpe_reg_patronal", length=15)
    public String getCpeRegPatronal() {
        return this.cpeRegPatronal;
    }

    public void setCpeRegPatronal(String cpeRegPatronal) {
        this.cpeRegPatronal = cpeRegPatronal;
    }


    @Column(name="cpe_giro_cia", length=80)
    public String getCpeGiroCia() {
        return this.cpeGiroCia;
    }

    public void setCpeGiroCia(String cpeGiroCia) {
        this.cpeGiroCia = cpeGiroCia;
    }


    @Column(name="cpe_situacion_reg", length=1)
    public String getCpeSituacionReg() {
        return this.cpeSituacionReg;
    }

    public void setCpeSituacionReg(String cpeSituacionReg) {
        this.cpeSituacionReg = cpeSituacionReg;
    }


    @Column(name="cpe_ciudad_cia", length=30)
    public String getCpeCiudadCia() {
        return this.cpeCiudadCia;
    }

    public void setCpeCiudadCia(String cpeCiudadCia) {
        this.cpeCiudadCia = cpeCiudadCia;
    }


    @Column(name="smx_rfc", length=17)
    public String getSmxRfc() {
        return this.smxRfc;
    }

    public void setSmxRfc(String smxRfc) {
        this.smxRfc = smxRfc;
    }


    @Column(name="car_num_prestadora", length=60)
    public String getCarNumPrestadora() {
        return this.carNumPrestadora;
    }

    public void setCarNumPrestadora(String carNumPrestadora) {
        this.carNumPrestadora = carNumPrestadora;
    }


    @Column(name="cuy_ck_caja_comp", length=1)
    public String getCuyCkCajaComp() {
        return this.cuyCkCajaComp;
    }

    public void setCuyCkCajaComp(String cuyCkCajaComp) {
        this.cuyCkCajaComp = cuyCkCajaComp;
    }




}


