package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:12:18 AM by Hibernate Tools 5.2.0.Final


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * StdLegEntId generated by hbm2java
 */
@Embeddable
public class StdLegEntId  implements java.io.Serializable {


    private String stdIdLegEnt;
    private String idOrganization;

    public StdLegEntId() {
    }

    public StdLegEntId(String stdIdLegEnt, String idOrganization) {
        this.stdIdLegEnt = stdIdLegEnt;
        this.idOrganization = idOrganization;
    }



    @Column(name="std_id_leg_ent", nullable=false, length=9)
    public String getStdIdLegEnt() {
        return this.stdIdLegEnt;
    }

    public void setStdIdLegEnt(String stdIdLegEnt) {
        this.stdIdLegEnt = stdIdLegEnt;
    }


    @Column(name="id_organization", nullable=false, length=4)
    public String getIdOrganization() {
        return this.idOrganization;
    }

    public void setIdOrganization(String idOrganization) {
        this.idOrganization = idOrganization;
    }


    public boolean equals(Object other) {
        if ( (this == other ) ) return true;
        if ( (other == null ) ) return false;
        if ( !(other instanceof StdLegEntId) ) return false;
        StdLegEntId castOther = ( StdLegEntId ) other;

        return ( (this.getStdIdLegEnt()==castOther.getStdIdLegEnt()) || ( this.getStdIdLegEnt()!=null && castOther.getStdIdLegEnt()!=null && this.getStdIdLegEnt().equals(castOther.getStdIdLegEnt()) ) )
               && ( (this.getIdOrganization()==castOther.getIdOrganization()) || ( this.getIdOrganization()!=null && castOther.getIdOrganization()!=null && this.getIdOrganization().equals(castOther.getIdOrganization()) ) );
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + ( getStdIdLegEnt() == null ? 0 : this.getStdIdLegEnt().hashCode() );
        result = 37 * result + ( getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode() );
        return result;
    }


}


