package com.prosegur.sllpe.domain;


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdPerson generated by hbm2java
 */
@Entity
@Table(name="std_person"
            ,schema="public"
      )
public class StdPerson  implements java.io.Serializable {


    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StdPersonId id;
    private String stdNFamName1;
    private String stdNMaidenName;
    private String stdNFirstName;
    private String stdNUsualName;
    private String stdIdGender;
    private String stdIdSalutation;
    private Date stdDtBirth;
    private String stdIdCountry;
    private String stdIdGeoDiv;
    private String stdIdSubGeoDiv;
    private String stdComment;
    private String sspIdPaisEmisor;
    private String sspPrimApellido;
    private String stdSsn;
    private String scoPhoto;
    private String scoHomePage;
    private String sspIdTpDoc;
    private String sfrNMaidenName;
    private String sfrNmBirthPlace;
    private String stdIdGeoPlace;
    private String stdSsKey;
    private String stdSsNumber;
    private String sarNMarriedName;
    private String sbrIdRaca;
    private String scoPhotoInet;
    private String sgeIdAddName;
    private String sgeIdTitel;
    private String sgeIdVsw;
    private String sgeNNameCompl;
    private String sukMaidenName;
    private String sukOtherForename;
    private String sukPreviousSurna;
    private Date susDeathDate;
    private Short scoSmoker;
    private String scoGbName;
    private String scoIdRegion;
    private String sarExpedido;
    private Short susVeteran;
    private String susIdVetDisTy;
    private String susIdVeteranWhe;
    private String susIdEthnicity;
    private Date sarDtDefuncion;
    private String scbDigVer;
    private String smeNumSs;
    private String sarCuil;
    private String sclRut;
    private String smeRfc;
    private String smeCurp;
    private String sbrCpf;
    private String smxImss;
    private String cmxApellidoPaternoImss;
    private String cmxApellidoMaternoImss;
    private String cmxNombreImss;
    private String idApprole;
    private String idSecuser;
    private Date dtLastUpdate;
    private String cfrLocalidadNac;
    private String stdIdCountryPadre;
    private String stdIdCountryMadre;
    private String ccoNecHabi;
    private String plcoHiddenByDataProtection;
    private Date plcoDate4HiddenDataProtec;
    private String scoGbLegal;
    private String plcoIdOrganization;
    private String nombreApellido;

    public StdPerson() {
    }


    public StdPerson(StdPersonId id) {
        this.id = id;
    }
    public StdPerson(StdPersonId id, String stdNFamName1, String stdNMaidenName, String stdNFirstName, String stdNUsualName, String stdIdGender, String stdIdSalutation, Date stdDtBirth, String stdIdCountry, String stdIdGeoDiv, String stdIdSubGeoDiv, String stdComment, String sspIdPaisEmisor, String sspPrimApellido, String stdSsn, String scoPhoto, String scoHomePage, String sspIdTpDoc, String sfrNMaidenName, String sfrNmBirthPlace, String stdIdGeoPlace, String stdSsKey, String stdSsNumber, String sarNMarriedName, String sbrIdRaca, String scoPhotoInet, String sgeIdAddName, String sgeIdTitel, String sgeIdVsw, String sgeNNameCompl, String sukMaidenName, String sukOtherForename, String sukPreviousSurna, Date susDeathDate, Short scoSmoker, String scoGbName, String scoIdRegion, String sarExpedido, Short susVeteran, String susIdVetDisTy, String susIdVeteranWhe, String susIdEthnicity, Date sarDtDefuncion, String scbDigVer, String smeNumSs, String sarCuil, String sclRut, String smeRfc, String smeCurp, String sbrCpf, String smxImss, String cmxApellidoPaternoImss, String cmxApellidoMaternoImss, String cmxNombreImss, String idApprole, String idSecuser, Date dtLastUpdate, String cfrLocalidadNac, String stdIdCountryPadre, String stdIdCountryMadre, String ccoNecHabi, String plcoHiddenByDataProtection, Date plcoDate4HiddenDataProtec, String scoGbLegal, String plcoIdOrganization) {
        this.id = id;
        this.stdNFamName1 = stdNFamName1;
        this.stdNMaidenName = stdNMaidenName;
        this.stdNFirstName = stdNFirstName;
        this.stdNUsualName = stdNUsualName;
        this.stdIdGender = stdIdGender;
        this.stdIdSalutation = stdIdSalutation;
        this.stdDtBirth = stdDtBirth;
        this.stdIdCountry = stdIdCountry;
        this.stdIdGeoDiv = stdIdGeoDiv;
        this.stdIdSubGeoDiv = stdIdSubGeoDiv;
        this.stdComment = stdComment;
        this.sspIdPaisEmisor = sspIdPaisEmisor;
        this.sspPrimApellido = sspPrimApellido;
        this.stdSsn = stdSsn;
        this.scoPhoto = scoPhoto;
        this.scoHomePage = scoHomePage;
        this.sspIdTpDoc = sspIdTpDoc;
        this.sfrNMaidenName = sfrNMaidenName;
        this.sfrNmBirthPlace = sfrNmBirthPlace;
        this.stdIdGeoPlace = stdIdGeoPlace;
        this.stdSsKey = stdSsKey;
        this.stdSsNumber = stdSsNumber;
        this.sarNMarriedName = sarNMarriedName;
        this.sbrIdRaca = sbrIdRaca;
        this.scoPhotoInet = scoPhotoInet;
        this.sgeIdAddName = sgeIdAddName;
        this.sgeIdTitel = sgeIdTitel;
        this.sgeIdVsw = sgeIdVsw;
        this.sgeNNameCompl = sgeNNameCompl;
        this.sukMaidenName = sukMaidenName;
        this.sukOtherForename = sukOtherForename;
        this.sukPreviousSurna = sukPreviousSurna;
        this.susDeathDate = susDeathDate;
        this.scoSmoker = scoSmoker;
        this.scoGbName = scoGbName;
        this.scoIdRegion = scoIdRegion;
        this.sarExpedido = sarExpedido;
        this.susVeteran = susVeteran;
        this.susIdVetDisTy = susIdVetDisTy;
        this.susIdVeteranWhe = susIdVeteranWhe;
        this.susIdEthnicity = susIdEthnicity;
        this.sarDtDefuncion = sarDtDefuncion;
        this.scbDigVer = scbDigVer;
        this.smeNumSs = smeNumSs;
        this.sarCuil = sarCuil;
        this.sclRut = sclRut;
        this.smeRfc = smeRfc;
        this.smeCurp = smeCurp;
        this.sbrCpf = sbrCpf;
        this.smxImss = smxImss;
        this.cmxApellidoPaternoImss = cmxApellidoPaternoImss;
        this.cmxApellidoMaternoImss = cmxApellidoMaternoImss;
        this.cmxNombreImss = cmxNombreImss;
        this.idApprole = idApprole;
        this.idSecuser = idSecuser;
        this.dtLastUpdate = dtLastUpdate;
        this.cfrLocalidadNac = cfrLocalidadNac;
        this.stdIdCountryPadre = stdIdCountryPadre;
        this.stdIdCountryMadre = stdIdCountryMadre;
        this.ccoNecHabi = ccoNecHabi;
        this.plcoHiddenByDataProtection = plcoHiddenByDataProtection;
        this.plcoDate4HiddenDataProtec = plcoDate4HiddenDataProtec;
        this.scoGbLegal = scoGbLegal;
        this.plcoIdOrganization = plcoIdOrganization;
        //p.std_n_fam_name_1 || '' '' || p.std_n_first_name
        this.nombreApellido =  this.stdNFamName1 + " " + this.stdNFirstName;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="stdIdPerson", column=@Column(name="std_id_person", nullable=false, length=10) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public StdPersonId getId() {
        return this.id;
    }

    public void setId(StdPersonId id) {
        this.id = id;
    }


    @Column(name="std_n_fam_name_1", length=50)
    public String getStdNFamName1() {
        return this.stdNFamName1;
    }

    public void setStdNFamName1(String stdNFamName1) {
        this.stdNFamName1 = stdNFamName1;
    }


    @Column(name="std_n_maiden_name", length=50)
    public String getStdNMaidenName() {
        return this.stdNMaidenName;
    }

    public void setStdNMaidenName(String stdNMaidenName) {
        this.stdNMaidenName = stdNMaidenName;
    }


    @Column(name="std_n_first_name", length=50)
    public String getStdNFirstName() {
        return this.stdNFirstName;
    }

    public void setStdNFirstName(String stdNFirstName) {
        this.stdNFirstName = stdNFirstName;
    }


    @Column(name="std_n_usual_name", length=50)
    public String getStdNUsualName() {
        return this.stdNUsualName;
    }

    public void setStdNUsualName(String stdNUsualName) {
        this.stdNUsualName = stdNUsualName;
    }


    @Column(name="std_id_gender", length=1)
    public String getStdIdGender() {
        return this.stdIdGender;
    }

    public void setStdIdGender(String stdIdGender) {
        this.stdIdGender = stdIdGender;
    }


    @Column(name="std_id_salutation", length=10)
    public String getStdIdSalutation() {
        return this.stdIdSalutation;
    }

    public void setStdIdSalutation(String stdIdSalutation) {
        this.stdIdSalutation = stdIdSalutation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="std_dt_birth", length=22)
    public Date getStdDtBirth() {
        return this.stdDtBirth;
    }

    public void setStdDtBirth(Date stdDtBirth) {
        this.stdDtBirth = stdDtBirth;
    }


    @Column(name="std_id_country", length=4)
    public String getStdIdCountry() {
        return this.stdIdCountry;
    }

    public void setStdIdCountry(String stdIdCountry) {
        this.stdIdCountry = stdIdCountry;
    }


    @Column(name="std_id_geo_div", length=4)
    public String getStdIdGeoDiv() {
        return this.stdIdGeoDiv;
    }

    public void setStdIdGeoDiv(String stdIdGeoDiv) {
        this.stdIdGeoDiv = stdIdGeoDiv;
    }


    @Column(name="std_id_sub_geo_div", length=8)
    public String getStdIdSubGeoDiv() {
        return this.stdIdSubGeoDiv;
    }

    public void setStdIdSubGeoDiv(String stdIdSubGeoDiv) {
        this.stdIdSubGeoDiv = stdIdSubGeoDiv;
    }


    @Column(name="std_comment", length=254)
    public String getStdComment() {
        return this.stdComment;
    }

    public void setStdComment(String stdComment) {
        this.stdComment = stdComment;
    }


    @Column(name="ssp_id_pais_emisor", length=4)
    public String getSspIdPaisEmisor() {
        return this.sspIdPaisEmisor;
    }

    public void setSspIdPaisEmisor(String sspIdPaisEmisor) {
        this.sspIdPaisEmisor = sspIdPaisEmisor;
    }


    @Column(name="ssp_prim_apellido", length=50)
    public String getSspPrimApellido() {
        return this.sspPrimApellido;
    }

    public void setSspPrimApellido(String sspPrimApellido) {
        this.sspPrimApellido = sspPrimApellido;
    }


    @Column(name="std_ssn", length=20)
    public String getStdSsn() {
        return this.stdSsn;
    }

    public void setStdSsn(String stdSsn) {
        this.stdSsn = stdSsn;
    }


    @Column(name="sco_photo", length=100)
    public String getScoPhoto() {
        return this.scoPhoto;
    }

    public void setScoPhoto(String scoPhoto) {
        this.scoPhoto = scoPhoto;
    }


    @Column(name="sco_home_page", length=254)
    public String getScoHomePage() {
        return this.scoHomePage;
    }

    public void setScoHomePage(String scoHomePage) {
        this.scoHomePage = scoHomePage;
    }


    @Column(name="ssp_id_tp_doc", length=10)
    public String getSspIdTpDoc() {
        return this.sspIdTpDoc;
    }

    public void setSspIdTpDoc(String sspIdTpDoc) {
        this.sspIdTpDoc = sspIdTpDoc;
    }


    @Column(name="sfr_n_maiden_name", length=50)
    public String getSfrNMaidenName() {
        return this.sfrNMaidenName;
    }

    public void setSfrNMaidenName(String sfrNMaidenName) {
        this.sfrNMaidenName = sfrNMaidenName;
    }


    @Column(name="sfr_nm_birth_place", length=50)
    public String getSfrNmBirthPlace() {
        return this.sfrNmBirthPlace;
    }

    public void setSfrNmBirthPlace(String sfrNmBirthPlace) {
        this.sfrNmBirthPlace = sfrNmBirthPlace;
    }


    @Column(name="std_id_geo_place", length=9)
    public String getStdIdGeoPlace() {
        return this.stdIdGeoPlace;
    }

    public void setStdIdGeoPlace(String stdIdGeoPlace) {
        this.stdIdGeoPlace = stdIdGeoPlace;
    }


    @Column(name="std_ss_key", length=3)
    public String getStdSsKey() {
        return this.stdSsKey;
    }

    public void setStdSsKey(String stdSsKey) {
        this.stdSsKey = stdSsKey;
    }


    @Column(name="std_ss_number", length=16)
    public String getStdSsNumber() {
        return this.stdSsNumber;
    }

    public void setStdSsNumber(String stdSsNumber) {
        this.stdSsNumber = stdSsNumber;
    }


    @Column(name="sar_n_married_name", length=40)
    public String getSarNMarriedName() {
        return this.sarNMarriedName;
    }

    public void setSarNMarriedName(String sarNMarriedName) {
        this.sarNMarriedName = sarNMarriedName;
    }


    @Column(name="sbr_id_raca", length=3)
    public String getSbrIdRaca() {
        return this.sbrIdRaca;
    }

    public void setSbrIdRaca(String sbrIdRaca) {
        this.sbrIdRaca = sbrIdRaca;
    }


    @Column(name="sco_photo_inet", length=100)
    public String getScoPhotoInet() {
        return this.scoPhotoInet;
    }

    public void setScoPhotoInet(String scoPhotoInet) {
        this.scoPhotoInet = scoPhotoInet;
    }


    @Column(name="sge_id_add_name", length=2)
    public String getSgeIdAddName() {
        return this.sgeIdAddName;
    }

    public void setSgeIdAddName(String sgeIdAddName) {
        this.sgeIdAddName = sgeIdAddName;
    }


    @Column(name="sge_id_titel", length=3)
    public String getSgeIdTitel() {
        return this.sgeIdTitel;
    }

    public void setSgeIdTitel(String sgeIdTitel) {
        this.sgeIdTitel = sgeIdTitel;
    }


    @Column(name="sge_id_vsw", length=3)
    public String getSgeIdVsw() {
        return this.sgeIdVsw;
    }

    public void setSgeIdVsw(String sgeIdVsw) {
        this.sgeIdVsw = sgeIdVsw;
    }


    @Column(name="sge_n_name_compl", length=254)
    public String getSgeNNameCompl() {
        return this.sgeNNameCompl;
    }

    public void setSgeNNameCompl(String sgeNNameCompl) {
        this.sgeNNameCompl = sgeNNameCompl;
    }


    @Column(name="suk_maiden_name", length=50)
    public String getSukMaidenName() {
        return this.sukMaidenName;
    }

    public void setSukMaidenName(String sukMaidenName) {
        this.sukMaidenName = sukMaidenName;
    }


    @Column(name="suk_other_forename", length=50)
    public String getSukOtherForename() {
        return this.sukOtherForename;
    }

    public void setSukOtherForename(String sukOtherForename) {
        this.sukOtherForename = sukOtherForename;
    }


    @Column(name="suk_previous_surna", length=50)
    public String getSukPreviousSurna() {
        return this.sukPreviousSurna;
    }

    public void setSukPreviousSurna(String sukPreviousSurna) {
        this.sukPreviousSurna = sukPreviousSurna;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sus_death_date", length=22)
    public Date getSusDeathDate() {
        return this.susDeathDate;
    }

    public void setSusDeathDate(Date susDeathDate) {
        this.susDeathDate = susDeathDate;
    }


    @Column(name="sco_smoker")
    public Short getScoSmoker() {
        return this.scoSmoker;
    }

    public void setScoSmoker(Short scoSmoker) {
        this.scoSmoker = scoSmoker;
    }


    @Column(name="sco_gb_name", length=254)
    public String getScoGbName() {
        return this.scoGbName;
    }

    public void setScoGbName(String scoGbName) {
        this.scoGbName = scoGbName;
    }


    @Column(name="sco_id_region", length=9)
    public String getScoIdRegion() {
        return this.scoIdRegion;
    }

    public void setScoIdRegion(String scoIdRegion) {
        this.scoIdRegion = scoIdRegion;
    }


    @Column(name="sar_expedido", length=62)
    public String getSarExpedido() {
        return this.sarExpedido;
    }

    public void setSarExpedido(String sarExpedido) {
        this.sarExpedido = sarExpedido;
    }


    @Column(name="sus_veteran")
    public Short getSusVeteran() {
        return this.susVeteran;
    }

    public void setSusVeteran(Short susVeteran) {
        this.susVeteran = susVeteran;
    }


    @Column(name="sus_id_vet_dis_ty", length=2)
    public String getSusIdVetDisTy() {
        return this.susIdVetDisTy;
    }

    public void setSusIdVetDisTy(String susIdVetDisTy) {
        this.susIdVetDisTy = susIdVetDisTy;
    }


    @Column(name="sus_id_veteran_whe", length=3)
    public String getSusIdVeteranWhe() {
        return this.susIdVeteranWhe;
    }

    public void setSusIdVeteranWhe(String susIdVeteranWhe) {
        this.susIdVeteranWhe = susIdVeteranWhe;
    }


    @Column(name="sus_id_ethnicity", length=3)
    public String getSusIdEthnicity() {
        return this.susIdEthnicity;
    }

    public void setSusIdEthnicity(String susIdEthnicity) {
        this.susIdEthnicity = susIdEthnicity;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="sar_dt_defuncion", length=22)
    public Date getSarDtDefuncion() {
        return this.sarDtDefuncion;
    }

    public void setSarDtDefuncion(Date sarDtDefuncion) {
        this.sarDtDefuncion = sarDtDefuncion;
    }


    @Column(name="scb_dig_ver", length=1)
    public String getScbDigVer() {
        return this.scbDigVer;
    }

    public void setScbDigVer(String scbDigVer) {
        this.scbDigVer = scbDigVer;
    }


    @Column(name="sme_num_ss", length=62)
    public String getSmeNumSs() {
        return this.smeNumSs;
    }

    public void setSmeNumSs(String smeNumSs) {
        this.smeNumSs = smeNumSs;
    }


    @Column(name="sar_cuil", length=16)
    public String getSarCuil() {
        return this.sarCuil;
    }

    public void setSarCuil(String sarCuil) {
        this.sarCuil = sarCuil;
    }


    @Column(name="scl_rut", length=16)
    public String getSclRut() {
        return this.sclRut;
    }

    public void setSclRut(String sclRut) {
        this.sclRut = sclRut;
    }


    @Column(name="sme_rfc", length=16)
    public String getSmeRfc() {
        return this.smeRfc;
    }

    public void setSmeRfc(String smeRfc) {
        this.smeRfc = smeRfc;
    }


    @Column(name="sme_curp", length=20)
    public String getSmeCurp() {
        return this.smeCurp;
    }

    public void setSmeCurp(String smeCurp) {
        this.smeCurp = smeCurp;
    }


    @Column(name="sbr_cpf", length=20)
    public String getSbrCpf() {
        return this.sbrCpf;
    }

    public void setSbrCpf(String sbrCpf) {
        this.sbrCpf = sbrCpf;
    }


    @Column(name="smx_imss", length=12)
    public String getSmxImss() {
        return this.smxImss;
    }

    public void setSmxImss(String smxImss) {
        this.smxImss = smxImss;
    }


    @Column(name="cmx_apellido_paterno_imss", length=50)
    public String getCmxApellidoPaternoImss() {
        return this.cmxApellidoPaternoImss;
    }

    public void setCmxApellidoPaternoImss(String cmxApellidoPaternoImss) {
        this.cmxApellidoPaternoImss = cmxApellidoPaternoImss;
    }


    @Column(name="cmx_apellido_materno_imss", length=50)
    public String getCmxApellidoMaternoImss() {
        return this.cmxApellidoMaternoImss;
    }

    public void setCmxApellidoMaternoImss(String cmxApellidoMaternoImss) {
        this.cmxApellidoMaternoImss = cmxApellidoMaternoImss;
    }


    @Column(name="cmx_nombre_imss", length=50)
    public String getCmxNombreImss() {
        return this.cmxNombreImss;
    }

    public void setCmxNombreImss(String cmxNombreImss) {
        this.cmxNombreImss = cmxNombreImss;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="cfr_localidad_nac", length=100)
    public String getCfrLocalidadNac() {
        return this.cfrLocalidadNac;
    }

    public void setCfrLocalidadNac(String cfrLocalidadNac) {
        this.cfrLocalidadNac = cfrLocalidadNac;
    }


    @Column(name="std_id_country_padre", length=4)
    public String getStdIdCountryPadre() {
        return this.stdIdCountryPadre;
    }

    public void setStdIdCountryPadre(String stdIdCountryPadre) {
        this.stdIdCountryPadre = stdIdCountryPadre;
    }


    @Column(name="std_id_country_madre", length=4)
    public String getStdIdCountryMadre() {
        return this.stdIdCountryMadre;
    }

    public void setStdIdCountryMadre(String stdIdCountryMadre) {
        this.stdIdCountryMadre = stdIdCountryMadre;
    }


    @Column(name="cco_nec_habi", length=1)
    public String getCcoNecHabi() {
        return this.ccoNecHabi;
    }

    public void setCcoNecHabi(String ccoNecHabi) {
        this.ccoNecHabi = ccoNecHabi;
    }


    @Column(name="plco_hidden_by_data_protection", length=1)
    public String getPlcoHiddenByDataProtection() {
        return this.plcoHiddenByDataProtection;
    }

    public void setPlcoHiddenByDataProtection(String plcoHiddenByDataProtection) {
        this.plcoHiddenByDataProtection = plcoHiddenByDataProtection;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="plco_date_4_hidden_data_protec", length=22)
    public Date getPlcoDate4HiddenDataProtec() {
        return this.plcoDate4HiddenDataProtec;
    }

    public void setPlcoDate4HiddenDataProtec(Date plcoDate4HiddenDataProtec) {
        this.plcoDate4HiddenDataProtec = plcoDate4HiddenDataProtec;
    }


    @Column(name="sco_gb_legal", length=50)
    public String getScoGbLegal() {
        return this.scoGbLegal;
    }

    public void setScoGbLegal(String scoGbLegal) {
        this.scoGbLegal = scoGbLegal;
    }


    @Column(name="plco_id_organization", length=4)
    public String getPlcoIdOrganization() {
        return this.plcoIdOrganization;
    }

    public void setPlcoIdOrganization(String plcoIdOrganization) {
        this.plcoIdOrganization = plcoIdOrganization;
    }

    
    @Column(insertable=false, updatable=false)
	public String nombreApellido() {
		return nombreApellido;
	}
	
    /*
	public void setNombreApellido() {
		this.nombreApellido =  this.stdNFamName1 + " " + this.stdNFirstName;
    }
    */
   
    
    




}


