package com.prosegur.sllpe.domain;
// Generated Apr 1, 2021, 12:12:48 AM by Hibernate Tools 5.2.0.Final


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StdSubGeoDiv generated by hbm2java
 */
@Entity
@Table(name="std_sub_geo_div"
            ,schema="public"
      )
public class StdSubGeoDiv  implements java.io.Serializable {


    private StdSubGeoDivId id;
    private String stdNSubGeoEng;
    private String stdNSubGeoEsp;
    private String stdNSubGeoFra;
    private String stdNSubGeoGer;
    private String stdNSubGeoBra;
    private String stdNSubGeoIta;
    private String stdNSubGeoGen;
    private String idApprole;
    private String sarIdProvAfip;
    private String idSecuser;
    private String scbIdZonaUpc;
    private Date dtLastUpdate;
    private String smeIdZonaEc;

    public StdSubGeoDiv() {
    }


    public StdSubGeoDiv(StdSubGeoDivId id) {
        this.id = id;
    }
    public StdSubGeoDiv(StdSubGeoDivId id, String stdNSubGeoEng, String stdNSubGeoEsp, String stdNSubGeoFra, String stdNSubGeoGer, String stdNSubGeoBra, String stdNSubGeoIta, String stdNSubGeoGen, String idApprole, String sarIdProvAfip, String idSecuser, String scbIdZonaUpc, Date dtLastUpdate, String smeIdZonaEc) {
        this.id = id;
        this.stdNSubGeoEng = stdNSubGeoEng;
        this.stdNSubGeoEsp = stdNSubGeoEsp;
        this.stdNSubGeoFra = stdNSubGeoFra;
        this.stdNSubGeoGer = stdNSubGeoGer;
        this.stdNSubGeoBra = stdNSubGeoBra;
        this.stdNSubGeoIta = stdNSubGeoIta;
        this.stdNSubGeoGen = stdNSubGeoGen;
        this.idApprole = idApprole;
        this.sarIdProvAfip = sarIdProvAfip;
        this.idSecuser = idSecuser;
        this.scbIdZonaUpc = scbIdZonaUpc;
        this.dtLastUpdate = dtLastUpdate;
        this.smeIdZonaEc = smeIdZonaEc;
    }

    @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="stdIdCountry", column=@Column(name="std_id_country", nullable=false, length=4) ),
        @AttributeOverride(name="stdIdGeoDiv", column=@Column(name="std_id_geo_div", nullable=false, length=4) ),
        @AttributeOverride(name="stdIdSubGeoDiv", column=@Column(name="std_id_sub_geo_div", nullable=false, length=8) ),
        @AttributeOverride(name="idOrganization", column=@Column(name="id_organization", nullable=false, length=4) )
    } )
    public StdSubGeoDivId getId() {
        return this.id;
    }

    public void setId(StdSubGeoDivId id) {
        this.id = id;
    }


    @Column(name="std_n_sub_geo_eng", length=62)
    public String getStdNSubGeoEng() {
        return this.stdNSubGeoEng;
    }

    public void setStdNSubGeoEng(String stdNSubGeoEng) {
        this.stdNSubGeoEng = stdNSubGeoEng;
    }


    @Column(name="std_n_sub_geo_esp", length=62)
    public String getStdNSubGeoEsp() {
        return this.stdNSubGeoEsp;
    }

    public void setStdNSubGeoEsp(String stdNSubGeoEsp) {
        this.stdNSubGeoEsp = stdNSubGeoEsp;
    }


    @Column(name="std_n_sub_geo_fra", length=62)
    public String getStdNSubGeoFra() {
        return this.stdNSubGeoFra;
    }

    public void setStdNSubGeoFra(String stdNSubGeoFra) {
        this.stdNSubGeoFra = stdNSubGeoFra;
    }


    @Column(name="std_n_sub_geo_ger", length=62)
    public String getStdNSubGeoGer() {
        return this.stdNSubGeoGer;
    }

    public void setStdNSubGeoGer(String stdNSubGeoGer) {
        this.stdNSubGeoGer = stdNSubGeoGer;
    }


    @Column(name="std_n_sub_geo_bra", length=62)
    public String getStdNSubGeoBra() {
        return this.stdNSubGeoBra;
    }

    public void setStdNSubGeoBra(String stdNSubGeoBra) {
        this.stdNSubGeoBra = stdNSubGeoBra;
    }


    @Column(name="std_n_sub_geo_ita", length=62)
    public String getStdNSubGeoIta() {
        return this.stdNSubGeoIta;
    }

    public void setStdNSubGeoIta(String stdNSubGeoIta) {
        this.stdNSubGeoIta = stdNSubGeoIta;
    }


    @Column(name="std_n_sub_geo_gen", length=62)
    public String getStdNSubGeoGen() {
        return this.stdNSubGeoGen;
    }

    public void setStdNSubGeoGen(String stdNSubGeoGen) {
        this.stdNSubGeoGen = stdNSubGeoGen;
    }


    @Column(name="id_approle", length=30)
    public String getIdApprole() {
        return this.idApprole;
    }

    public void setIdApprole(String idApprole) {
        this.idApprole = idApprole;
    }


    @Column(name="sar_id_prov_afip", length=4)
    public String getSarIdProvAfip() {
        return this.sarIdProvAfip;
    }

    public void setSarIdProvAfip(String sarIdProvAfip) {
        this.sarIdProvAfip = sarIdProvAfip;
    }


    @Column(name="id_secuser", length=30)
    public String getIdSecuser() {
        return this.idSecuser;
    }

    public void setIdSecuser(String idSecuser) {
        this.idSecuser = idSecuser;
    }


    @Column(name="scb_id_zona_upc", length=3)
    public String getScbIdZonaUpc() {
        return this.scbIdZonaUpc;
    }

    public void setScbIdZonaUpc(String scbIdZonaUpc) {
        this.scbIdZonaUpc = scbIdZonaUpc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dt_last_update", length=22)
    public Date getDtLastUpdate() {
        return this.dtLastUpdate;
    }

    public void setDtLastUpdate(Date dtLastUpdate) {
        this.dtLastUpdate = dtLastUpdate;
    }


    @Column(name="sme_id_zona_ec", length=2)
    public String getSmeIdZonaEc() {
        return this.smeIdZonaEc;
    }

    public void setSmeIdZonaEc(String smeIdZonaEc) {
        this.smeIdZonaEc = smeIdZonaEc;
    }




}


