
  SELECT  L.* FROM (
                SELECT 
                    L.ID_ORGANIZATION, L.LIT_ID_LITIGIO, L.LIT_NRO_PROCESO, LIT_VALOR_TOTAL, LIT_BPO,
	  
	  		-------------------------------------------------------------inicio reu demandado------------------------------------------------------------
	  		(SELECT  string_agg(M4PEEX.ENT_NM_ENTIDAD::character varying, ',' order by M4AURE.LIT_ID_LITIGIO, M4PEEX.ENT_NRO_IDENTIFICACION ) as NOMBRE
  			FROM sll.M4SLL_AUTOR_REU M4AURE
                JOIN  sll.M4SLL_ENTIDADES M4PEEX ON (
                                    M4AURE.ID_ORGANIZATION = M4PEEX.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'R' AND M4PEEX.ENT_NRO_IDENTIFICACION = M4AURE.ENT_NRO_IDENTIFICACION)
            WHERE M4PEEX.ID_ORGANIZATION = L.ID_ORGANIZATION  AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
			) 
	  		|| ' '|| 
	  		(
				SELECT (string_agg(SLEN.STD_N_LEG_ENT ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, M4AURE.STD_ID_LEG_ENT)) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN public.STD_LEG_ENT SLEN  ON (  M4AURE.ID_ORGANIZATION =  SLEN.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'R' AND SLEN.STD_ID_LEG_ENT =  M4AURE.STD_ID_LEG_ENT)
                 WHERE SLEN.ID_ORGANIZATION =  L.ID_ORGANIZATION  AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
			)
	  		|| ' '|| 
	  		(
				SELECT (string_agg(M4PE.PEX_NOMBRE  ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, M4PE.PEX_NRO_DOCUMENTO )) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN sll.M4SLL_PERSONA_EXT M4PE ON (   M4PE.ID_ORGANIZATION = M4AURE.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'R' AND M4PE.PEX_NRO_DOCUMENTO =  M4AURE.PEX_NRO_DOCUMENTO)
                 WHERE M4PE.ID_ORGANIZATION = '0050' AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO  			
			)
	  		|| ' '|| 
	  		(
                SELECT (string_agg(STDP.STD_N_FIRST_NAME || ' ' || STDP.STD_N_FAM_NAME_1 ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, STDP.STD_ID_PERSON ) ) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN public.std_person STDP ON ( STDP.STD_ID_COUNTRY = '7' AND M4AURE.AUR_AUTOR_REU = 'R' AND STDP.STD_ID_PERSON = M4AURE.STD_ID_PERSON )
                 WHERE STDP.ID_ORGANIZATION = '0000' AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
            )
	  		AS REU,
	  	-------------------------------------------------------------------------inicio autor-----------------------------------------------------------------
	  		(SELECT  string_agg(M4PEEX.ENT_NM_ENTIDAD::character varying, ',' order by M4AURE.LIT_ID_LITIGIO, M4PEEX.ENT_NRO_IDENTIFICACION ) as NOMBRE
  			FROM sll.M4SLL_AUTOR_REU M4AURE
                JOIN  sll.M4SLL_ENTIDADES M4PEEX ON (
                                    M4AURE.ID_ORGANIZATION = M4PEEX.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'A' AND M4PEEX.ENT_NRO_IDENTIFICACION = M4AURE.ENT_NRO_IDENTIFICACION)
            WHERE M4PEEX.ID_ORGANIZATION = L.ID_ORGANIZATION  AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
			) 
	  		|| ' '|| 
	  		(
				SELECT (string_agg(SLEN.STD_N_LEG_ENT ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, M4AURE.STD_ID_LEG_ENT)) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN public.STD_LEG_ENT SLEN  ON (  M4AURE.ID_ORGANIZATION =  SLEN.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'A' AND SLEN.STD_ID_LEG_ENT =  M4AURE.STD_ID_LEG_ENT)
                 WHERE SLEN.ID_ORGANIZATION =  L.ID_ORGANIZATION  AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
			)
	  		|| ' '|| 
	  		(
				SELECT (string_agg(M4PE.PEX_NOMBRE  ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, M4PE.PEX_NRO_DOCUMENTO )) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN sll.M4SLL_PERSONA_EXT M4PE ON (   M4PE.ID_ORGANIZATION = M4AURE.ID_ORGANIZATION AND M4AURE.AUR_AUTOR_REU = 'A' AND M4PE.PEX_NRO_DOCUMENTO =  M4AURE.PEX_NRO_DOCUMENTO)
                 WHERE M4PE.ID_ORGANIZATION = '0050' AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO  			
			)
	  		|| ' '|| 
	  		(
                SELECT (string_agg(STDP.STD_N_FIRST_NAME || ' ' || STDP.STD_N_FAM_NAME_1 ,' | ' ORDER BY M4AURE.LIT_ID_LITIGIO, STDP.STD_ID_PERSON ) ) AS NOMBRE   
                FROM sll.M4SLL_AUTOR_REU M4AURE
                    JOIN public.std_person STDP ON ( STDP.STD_ID_COUNTRY = '7' AND M4AURE.AUR_AUTOR_REU = 'A' AND STDP.STD_ID_PERSON = M4AURE.STD_ID_PERSON )
                 WHERE STDP.ID_ORGANIZATION = '0000' AND M4AURE.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO 
            )
	  		AS AUTOR,            
(SELECT T.TRI_NM_TRIBUNAL FROM  sll.M4SLL_FASES F
    INNER JOIN (SELECT LIT_ID_LITIGIO, MIN(FAS_SECUENCIA) AS FaseMin FROM sll.M4SLL_FASES WHERE ID_ORGANIZATION = '0050' GROUP BY LIT_ID_LITIGIO)  minF 
        ON minF.FaseMin = F.FAS_SECUENCIA AND minF.LIT_ID_LITIGIO = F.LIT_ID_LITIGIO
    INNER JOIN sll.M4SLL_TRIBUNALES T ON (T.ID_ORGANIZATION = '0050' AND 
                                               T.ID_ORGANIZATION = F.ID_ORGANIZATION AND 
                                               T.TRI_ID_TRIBUNAL = F.TRI_ID_TRIBUNAL)
      WHERE F.ID_ORGANIZATION = '0050' AND  
          F.LIT_ID_LITIGIO = L.LIT_ID_LITIGIO) 
	  	AS TRI_NM_TRIBUNAL,
        ST.TST_NM_TP_STATUS AS TST_NM_TP_STATUS,
        TL.TPL_NM_TP_LITIGIO AS TPL_NM_TP_LITIGIO,
        STD.TSD_NM_TP_STATUS_DET AS TSD_NM_TP_STATUS_DET
    FROM sll.M4SLL_LITIGIOS L
    LEFT JOIN sll.M4SLL_TP_STATUS ST ON ST.TST_ID_TP_STATUS  = L.TST_ID_TP_STATUS AND L.ID_ORGANIZATION = ST.ID_ORGANIZATION
    LEFT JOIN sll.M4SLL_TP_STA_DET STD ON STD.TPL_ID_TP_LITIGIO = L.TPL_ID_TP_LITIGIO AND STD.TSD_ID_TP_STA_DET = L.TSD_ID_TP_STA_DET AND L.ID_ORGANIZATION = STD.ID_ORGANIZATION
    LEFT JOIN sll.M4SLL_TP_LITIGIOS TL ON TL.TPL_ID_TP_LITIGIO  = L.TPL_ID_TP_LITIGIO AND L.ID_ORGANIZATION = TL.ID_ORGANIZATION
    WHERE L.ID_ORGANIZATION = '0050') L
    WHERE L.ID_ORGANIZATION = '0050'