-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** D_LEG_ENT
-- SQLINES DEMO *** ------------------------------------

  CREATE TABLE public.STD_LEG_ENT 
   (	ID_ORGANIZATION VARCHAR(4), 
	STD_ID_LEG_ENT VARCHAR(9), 
	STD_N_LEG_ENT VARCHAR(62), 
	STD_DT_START TIMESTAMP(0), 
	STD_DT_END TIMESTAMP(0), 
	STD_DESCRIPTION VARCHAR(254), 
	SSP_ID_RESPONSABLE VARCHAR(10), 
	SSP_ID_TP_ID_LGAL VARCHAR(1), 
	SSP_ID_PAIS_EMISOR VARCHAR(4), 
	SFR_ID_LEGAL_HOLDI VARCHAR(9), 
	SFR_ID_ACTIV_SECTO VARCHAR(5), 
	SSP_ID_LEGAL VARCHAR(10), 
	SSP_CARGO_CERTENG VARCHAR(40), 
	SSP_CARGO_CERTESP VARCHAR(40), 
	SSP_CARGO_CERTFRA VARCHAR(40), 
	SSP_CARGO_CERTGER VARCHAR(40), 
	SSP_CARGO_CERTBRA VARCHAR(40), 
	SSP_CARGO_CERTITA VARCHAR(40), 
	SSP_CARGO_CERTGEN VARCHAR(40), 
	SSP_COD_LOC_EMPR VARCHAR(5), 
	SSP_FIRMT_CERT_HAB VARCHAR(40), 
	SSP_ID_LEG_CER_HAB VARCHAR(9), 
	SSP_ID_TP_ALF_EMP SMALLINT, 
	SSP_LIT_PLURIEMPLE VARCHAR(50), 
	SSP_NUM_TRAB_EMPR VARCHAR(10), 
	SSP_SUBCIF VARCHAR(2), 
	STD_NID_ENT VARCHAR(14), 
	STD_NID_ACT VARCHAR(5), 
	SFR_LEGAL_ENTITY_L VARCHAR(62), 
	SFR_REG_LEGENT SMALLINT, 
	SFR_REG_SUB_LEGENT SMALLINT, 
	SPO_ID_NATUREZA VARCHAR(6), 
	SPO_ID_ACTIVIDADE VARCHAR(6), 
	SPO_DT_PUBLIC_BT TIMESTAMP(0), 
	SPO_DT_ULT_TAB_SAL TIMESTAMP(0), 
	SPO_INST_REG_TRAB VARCHAR(60), 
	SPO_CAPITAL_SOCIAL DECIMAL(14,4), 
	SPO_VOLUME_VENDAS DECIMAL(14,4), 
	SPO_REPARTICAO_PER DECIMAL(5,1), 
	SPO_REP_PERC_ESTRA DECIMAL(5,1), 
	SPO_REP_PERC_PUB DECIMAL(5,1), 
	SPO_ANO_LEG_ENT VARCHAR(4), 
	SPO_COD_CONCELHO VARCHAR(4), 
	SAR_ID_ART VARCHAR(11), 
	CCO_CODIGO_INTERNO VARCHAR(2), 
	SME_SIEM INT, 
	CCO_ID_MODELO_NOTI VARCHAR(3), 
	CCO_DT_INICIO_CORT TIMESTAMP(0), 
	SME_ID_REG_FISCAL VARCHAR(4), 
	CAR_ID_BASE_LIQUIDACION SMALLINT, 
	CCO_DT_FIN_CORTE TIMESTAMP(0), 
	CCO_ULT_ID_HR VARCHAR(10), 
	CCO_ULT_PEDIDO_DIN BIGINT, 
	CCO_LOGO VARCHAR(254), 
	CCO_PLANTILLA BYTEA, 
	CCO_CK_BLOQUEAR SMALLINT, 
	CFR_ID_EMP_ANALITICA VARCHAR(8), 
	CCO_CODIGO_ERP VARCHAR(10), 
	CCO_CODIGO_AURUS VARCHAR(10), 
	CCO_ID_NEGOCIO VARCHAR(3), 
	ID_APPROLE VARCHAR(30), 
	ID_SECUSER VARCHAR(30), 
	DT_LAST_UPDATE TIMESTAMP(0), 
	SME_ID_COMISION_MIXTA VARCHAR(20), 
	SME_FEC_PRES_DIM TIMESTAMP(0), 
	SME_FOLIO_OPERAC VARCHAR(14), 
	SSP_CARGO_CERT_HAB VARCHAR(40), 
	CAR_ID_BASE_LIQUID SMALLINT, 
	COD_FILIAL_BRASIL VARCHAR(10), 
	CCL_INTERFASE VARCHAR(1), 
	CMX_FACTOR_SUELDO_NOMINAL DECIMAL(18,5), 
	CPE_CODIGO_CORP VARCHAR(2), 
	CPE_NUM_RUC_CIA VARCHAR(15), 
	CPE_REG_PATRONAL VARCHAR(15), 
	CPE_GIRO_CIA VARCHAR(80), 
	CPE_SITUACION_REG VARCHAR(1), 
	CPE_CIUDAD_CIA VARCHAR(30), 
	SMX_RFC VARCHAR(17), 
	CAR_NUM_PRESTADORA VARCHAR(60), 
	CUY_CK_CAJA_COMP VARCHAR(1)
   );
-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** D_LEG_ENT_FK11
-- SQLINES DEMO *** ------------------------------------

  CREATE INDEX STD_LEG_ENT_FK11 ON public.STD_LEG_ENT (STD_ID_LEG_ENT, CAR_ID_BASE_LIQUID, ID_ORGANIZATION) 
   ;
-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** _LEG_ENT
-- SQLINES DEMO *** ------------------------------------

  CREATE UNIQUE INDEX UNI_LEG_ENT ON public.STD_LEG_ENT (STD_ID_LEG_ENT, ID_ORGANIZATION) 
  ;
-- SQLINES DEMO *** ------------------------------------
-- SQLINES DEMO *** Table STD_LEG_ENT
-- SQLINES DEMO *** ------------------------------------

  ALTER TABLE STD_LEG_ENT ADD CONSTRAINT PK_LEG_ENT PRIMARY KEY (STD_ID_LEG_ENT, ID_ORGANIZATION)
  ;
