
  CREATE TABLE public."STD_COUNTRY" 
   (	"ID_ORGANIZATION" VARCHAR(4), 
	"STD_ID_COUNTRY" VARCHAR(4), 
	"STD_N_COUNTRYBRA" VARCHAR(62), 
	"STD_N_COUNTRYENG" VARCHAR(62), 
	"STD_N_COUNTRYESP" VARCHAR(62), 
	"STD_N_COUNTRYFRA" VARCHAR(62), 
	"STD_N_COUNTRYGEN" VARCHAR(62), 
	"STD_N_COUNTRYGER" VARCHAR(62), 
	"STD_N_COUNTRYITA" VARCHAR(62), 
	"STD_ID_COUNT_GROUP" VARCHAR(3), 
	"STD_ID_NACIONALITY" VARCHAR(3), 
	"STD_N_NACIONALBRA" VARCHAR(62), 
	"STD_N_NACIONALENG" VARCHAR(62), 
	"STD_N_NACIONALESP" VARCHAR(62), 
	"STD_N_NACIONALFRA" VARCHAR(62), 
	"STD_N_NACIONALGEN" VARCHAR(62), 
	"STD_N_NACIONALGER" VARCHAR(62), 
	"STD_N_NACIONALITA" VARCHAR(62), 
	"STD_ID_CURRENCY" VARCHAR(3), 
	"SFR_ID_NATIONALITY" VARCHAR(2), 
	"SSP_ID_NACION_SS" VARCHAR(3), 
	"ID_APPROLE" VARCHAR(30), 
	"ID_SECUSER" VARCHAR(30), 
	"DT_LAST_UPDATE" TIMESTAMP(0), 
	"STD_ID_COUNT_DIAN" SMALLINT
   ) 
  ;

  CREATE TABLE public."STD_GEO_DIV" 
   (	"ID_ORGANIZATION" VARCHAR(4) DEFAULT '0000', 
	"STD_ID_COUNTRY" VARCHAR(4), 
	"STD_ID_GEO_DIV" VARCHAR(4), 
	"STD_N_GEO_DIVENG" VARCHAR(62), 
	"STD_N_GEO_DIVESP" VARCHAR(62), 
	"STD_N_GEO_DIVFRA" VARCHAR(62), 
	"STD_N_GEO_DIVGER" VARCHAR(62), 
	"STD_N_GEO_DIVBRA" VARCHAR(62), 
	"STD_N_GEO_DIVITA" VARCHAR(62), 
	"STD_N_GEO_DIVGEN" VARCHAR(62), 
	"SME_ID_CURP" VARCHAR(2), 
	"SME_PORC_ILIS" DECIMAL(7,4), 
	"SCB_ID_ZONA_UPC" VARCHAR(3), 
	"SAR_ID_PROV_AFIP" VARCHAR(4), 
	"SME_PORC_IMPUESTO" DECIMAL(5,2), 
	"ID_APPROLE" VARCHAR(30), 
	"SME_CALC_IMP" SMALLINT, 
	"ID_SECUSER" VARCHAR(30), 
	"SME_ID_ESTADO_DIM" VARCHAR(4), 
	"DT_LAST_UPDATE" TIMESTAMP(0)
   ) 
  ;


  CREATE TABLE public."STD_GEO_PLACE" 
   (	"ID_ORGANIZATION" VARCHAR(4), 
	"STD_ID_COUNTRY" VARCHAR(4), 
	"STD_ID_GEO_DIV" VARCHAR(4), 
	"STD_ID_SUB_GEO_DIV" VARCHAR(8), 
	"STD_ID_GEO_PLACE" VARCHAR(9), 
	"STD_N_GEO_PLACENG" VARCHAR(62), 
	"STD_N_GEO_PLACESP" VARCHAR(62), 
	"STD_N_GEO_PLACFRA" VARCHAR(62), 
	"STD_N_GEO_PLACGER" VARCHAR(62), 
	"STD_N_GEO_PLACBRA" VARCHAR(62), 
	"STD_N_GEO_PLACITA" VARCHAR(62), 
	"STD_N_GEO_PLACGEN" VARCHAR(62), 
	"STD_ID_LEGAL_PLACE" VARCHAR(9), 
	"SCB_ID_ZONA_UPC" VARCHAR(3), 
	"ID_APPROLE" VARCHAR(30), 
	"ID_SECUSER" VARCHAR(30), 
	"DT_LAST_UPDATE" TIMESTAMP(0)
   ) 
  ;

  CREATE TABLE public."STD_PERSON" 
   (	"ID_ORGANIZATION" VARCHAR(4), 
	"STD_ID_PERSON" VARCHAR(10), 
	"STD_N_FAM_NAME_1" VARCHAR(50), 
	"STD_N_MAIDEN_NAME" VARCHAR(50), 
	"STD_N_FIRST_NAME" VARCHAR(50), 
	"STD_N_USUAL_NAME" VARCHAR(50), 
	"STD_ID_GENDER" VARCHAR(1), 
	"STD_ID_SALUTATION" VARCHAR(10), 
	"STD_DT_BIRTH" TIMESTAMP(0), 
	"STD_ID_COUNTRY" VARCHAR(4), 
	"STD_ID_GEO_DIV" VARCHAR(4), 
	"STD_ID_SUB_GEO_DIV" VARCHAR(8), 
	"STD_COMMENT" VARCHAR(254), 
	"SSP_ID_PAIS_EMISOR" VARCHAR(4), 
	"SSP_PRIM_APELLIDO" VARCHAR(50), 
	"STD_SSN" VARCHAR(20), 
	"SCO_PHOTO" VARCHAR(100), 
	"SCO_HOME_PAGE" VARCHAR(254), 
	"SSP_ID_TP_DOC" VARCHAR(10), 
	"SFR_N_MAIDEN_NAME" VARCHAR(50), 
	"SFR_NM_BIRTH_PLACE" VARCHAR(50), 
	"STD_ID_GEO_PLACE" VARCHAR(9), 
	"STD_SS_KEY" VARCHAR(3), 
	"STD_SS_NUMBER" VARCHAR(16), 
	"SAR_N_MARRIED_NAME" VARCHAR(40), 
	"SBR_ID_RACA" VARCHAR(3), 
	"SCO_PHOTO_INET" VARCHAR(100), 
	"SGE_ID_ADD_NAME" VARCHAR(2), 
	"SGE_ID_TITEL" VARCHAR(3), 
	"SGE_ID_VSW" VARCHAR(3), 
	"SGE_N_NAME_COMPL" VARCHAR(254), 
	"SUK_MAIDEN_NAME" VARCHAR(50), 
	"SUK_OTHER_FORENAME" VARCHAR(50), 
	"SUK_PREVIOUS_SURNA" VARCHAR(50), 
	"SUS_DEATH_DATE" TIMESTAMP(0), 
	"SCO_SMOKER" SMALLINT, 
	"SCO_GB_NAME" VARCHAR(254), 
	"SCO_ID_REGION" VARCHAR(9), 
	"SAR_EXPEDIDO" VARCHAR(62), 
	"SUS_VETERAN" SMALLINT, 
	"SUS_ID_VET_DIS_TY" VARCHAR(2), 
	"SUS_ID_VETERAN_WHE" VARCHAR(3), 
	"SUS_ID_ETHNICITY" VARCHAR(3), 
	"SAR_DT_DEFUNCION" TIMESTAMP(0), 
	"SCB_DIG_VER" VARCHAR(1), 
	"SME_NUM_SS" VARCHAR(62), 
	"SAR_CUIL" VARCHAR(16), 
	"SCL_RUT" VARCHAR(16), 
	"SME_RFC" VARCHAR(16), 
	"SME_CURP" VARCHAR(20), 
	"SBR_CPF" VARCHAR(20), 
	"SMX_IMSS" VARCHAR(12), 
	"CMX_APELLIDO_PATERNO_IMSS" VARCHAR(50), 
	"CMX_APELLIDO_MATERNO_IMSS" VARCHAR(50), 
	"CMX_NOMBRE_IMSS" VARCHAR(50), 
	"ID_APPROLE" VARCHAR(30), 
	"ID_SECUSER" VARCHAR(30), 
	"DT_LAST_UPDATE" TIMESTAMP(0), 
	"CFR_LOCALIDAD_NAC" VARCHAR(100), 
	"STD_ID_COUNTRY_PADRE" VARCHAR(4), 
	"STD_ID_COUNTRY_MADRE" VARCHAR(4), 
	"CCO_NEC_HABI" VARCHAR(1), 
	"PLCO_HIDDEN_BY_DATA_PROTECTION" VARCHAR(1) DEFAULT 0, 
	"PLCO_DATE_4_HIDDEN_DATA_PROTEC" TIMESTAMP(0), 
	"SCO_GB_LEGAL" VARCHAR(50), 
	"PLCO_ID_ORGANIZATION" VARCHAR(4)
   ) 
  ;

  CREATE TABLE public."STD_SUB_GEO_DIV" 
   (	"ID_ORGANIZATION" VARCHAR(4), 
	"STD_ID_COUNTRY" VARCHAR(4), 
	"STD_ID_GEO_DIV" VARCHAR(4), 
	"STD_ID_SUB_GEO_DIV" VARCHAR(8), 
	"STD_N_SUB_GEO_ENG" VARCHAR(62), 
	"STD_N_SUB_GEO_ESP" VARCHAR(62), 
	"STD_N_SUB_GEO_FRA" VARCHAR(62), 
	"STD_N_SUB_GEO_GER" VARCHAR(62), 
	"STD_N_SUB_GEO_BRA" VARCHAR(62), 
	"STD_N_SUB_GEO_ITA" VARCHAR(62), 
	"STD_N_SUB_GEO_GEN" VARCHAR(62), 
	"ID_APPROLE" VARCHAR(30), 
	"SAR_ID_PROV_AFIP" VARCHAR(4), 
	"ID_SECUSER" VARCHAR(30), 
	"SCB_ID_ZONA_UPC" VARCHAR(3), 
	"DT_LAST_UPDATE" TIMESTAMP(0), 
	"SME_ID_ZONA_EC" VARCHAR(2)
   ) 
  ;

  CREATE UNIQUE INDEX "IDX_COUNTRY" ON public."STD_COUNTRY" ("STD_ID_COUNTRY", "ID_ORGANIZATION") 
  ;

  CREATE UNIQUE INDEX "IDX_GEO_DIV" ON public."STD_GEO_DIV" ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "ID_ORGANIZATION") 
  ;

  CREATE UNIQUE INDEX "IDX_GEO_PLACE" ON public."STD_GEO_PLACE" ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "STD_ID_SUB_GEO_DIV", "STD_ID_GEO_PLACE", "ID_ORGANIZATION") 
  ;

  CREATE INDEX "IDX_PERSON_FK41" ON public."STD_PERSON" ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "STD_ID_SUB_GEO_DIV") 
  ;

  CREATE INDEX "IDX_PERSON_FK31" ON public."STD_PERSON" ("STD_ID_GEO_DIV", "STD_ID_COUNTRY") 
  ;

  CREATE INDEX "IDX_PERSON_FK21" ON public."STD_PERSON" ("STD_ID_COUNTRY") 
  ;

  CREATE INDEX "IDX_PERSON_FK11" ON public."STD_PERSON" ("STD_ID_SALUTATION") 
  ;

  CREATE UNIQUE INDEX "IDX_PK_PERSON" ON public."STD_PERSON" ("STD_ID_PERSON", "ID_ORGANIZATION") 
  ;

  CREATE UNIQUE INDEX "IDX_PK_SUB_GEO_DIV" ON public."STD_SUB_GEO_DIV" ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "STD_ID_SUB_GEO_DIV", "ID_ORGANIZATION") 
  ;

  ALTER TABLE public."STD_COUNTRY" ADD CONSTRAINT "PK_COUNTRY" PRIMARY KEY ("STD_ID_COUNTRY", "ID_ORGANIZATION")
;
  ALTER TABLE public."STD_GEO_DIV" ADD CONSTRAINT "PK_GEO_DIV" PRIMARY KEY ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "ID_ORGANIZATION")
;

  ALTER TABLE public."STD_GEO_PLACE" ADD CONSTRAINT "PK_GEO_PLACE" PRIMARY KEY ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "STD_ID_SUB_GEO_DIV", "STD_ID_GEO_PLACE", "ID_ORGANIZATION")
 ;

  ALTER TABLE public."STD_PERSON" ADD CONSTRAINT "PK_PERSON" PRIMARY KEY ("STD_ID_PERSON", "ID_ORGANIZATION")
;

  ALTER TABLE public."STD_SUB_GEO_DIV" ADD CONSTRAINT "PK_SUB_GEO_DIV" PRIMARY KEY ("STD_ID_COUNTRY", "STD_ID_GEO_DIV", "STD_ID_SUB_GEO_DIV", "ID_ORGANIZATION")
 ;
